'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, CircleDollarSign, Menu, Plus, RotateCcw, Save, Search, Send, X } from 'lucide-react';
import type { Account, AccountCategory, AccountingMappingKey, JournalDraft, JournalWithLines, LedgerRow, TrialBalanceRow } from '../../domain/accounting';
import { ACCOUNTING_MAPPING_KEYS, ACCOUNTING_MAPPING_LABELS } from '../../domain/accounting';
import type { Company } from '../../domain/foundation';
import { buildFinancialStatements, journalTotals } from '../../application/accounting';
import { IndexedDBAccountingRepository } from '../../infrastructure/indexeddb/accounting-repository';
import { IndexedDBCompanyRepository, IndexedDBFoundationRepository } from '../../infrastructure/indexeddb/repositories';
import { ErpSidebar } from '../erp-sidebar';

export type AccountingModule = 'accounts'|'mapping'|'opening-balances'|'journals'|'general-journal'|'ledger'|'trial-balance'|'financial-statements';

const categoryLabels: Record<AccountCategory,string> = { asset:'أصول', liability:'التزامات', equity:'حقوق ملكية', revenue:'إيرادات', expense:'تكاليف ومصروفات' };
const statusLabels = { draft:'مسودة', approved:'معتمد', posted:'مرحّل', reversed:'معكوس', cancelled:'ملغي' };

export function AccountingApp({module}:{module:AccountingModule}) {
  const repository = useMemo(()=>new IndexedDBAccountingRepository(),[]);
  const foundation = useMemo(()=>new IndexedDBFoundationRepository(),[]);
  const companiesRepo = useMemo(()=>new IndexedDBCompanyRepository(),[]);
  const [company,setCompany]=useState<Company>();
  const [accounts,setAccounts]=useState<Account[]>([]);
  const [journals,setJournals]=useState<JournalWithLines[]>([]);
  const [trial,setTrial]=useState<TrialBalanceRow[]>([]);
  const [loading,setLoading]=useState(true);
  const [mobileNav,setMobileNav]=useState(false);
  const [message,setMessage]=useState('');

  const reload=useCallback(async()=>{
    const companyId=await foundation.getActiveCompanyId();
    if(!companyId){setCompany(undefined);setLoading(false);return;}
    const [activeCompany,accountRows,journalRows,trialRows]=await Promise.all([companiesRepo.get(companyId),repository.listAccounts(companyId),repository.listJournals(companyId),repository.getTrialBalance(companyId)]);
    setCompany(activeCompany);setAccounts(accountRows);setJournals(journalRows);setTrial(trialRows);setLoading(false);
  },[companiesRepo,foundation,repository]);
  useEffect(()=>{
    // IndexedDB is an external browser system; load after the client mounts.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void reload();
  },[reload]);

  if(loading)return <Loading/>;
  if(!company)return <main className="grid min-h-screen place-items-center bg-[#F6F8FB] p-6 text-center" dir="rtl"><div><h1 className="text-2xl font-black text-[#17324D]">أنشئ الشركة أولًا</h1><p className="mt-3 text-sm text-slate-500">النواة المحاسبية تحتاج شركة وسنة وفترات محاسبية.</p><Link href="/setup" className="mt-6 inline-flex rounded-xl bg-[#287C8E] px-6 py-3 font-bold text-white">فتح الإعداد</Link></div></main>;

  return <main className="min-h-screen bg-[#F6F8FB] text-[#1C2B3A]" dir="rtl"><div className="flex min-h-screen"><ErpSidebar open={mobileNav} onClose={()=>setMobileNav(false)}/><section className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-[72px] items-center gap-3 border-b border-[#DDE5EC] bg-white/95 px-4 backdrop-blur sm:px-8"><button className="lg:hidden" onClick={()=>setMobileNav(true)} aria-label="فتح القائمة"><Menu/></button><div><p className="text-sm font-extrabold">{company.arabicName}</p><p className="text-[11px] text-[#6E8093]">{company.code} · {company.baseCurrency}</p></div><span className="mr-auto rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold text-emerald-700">Accounting Core · Local</span></header>
    <div className="mx-auto max-w-[1380px] p-4 sm:p-8">{message&&<Notice text={message} close={()=>setMessage('')}/>}
      {module==='accounts'&&<AccountsView company={company} accounts={accounts} repository={repository} reload={reload} notify={setMessage}/>}
      {module==='mapping'&&<MappingView company={company} accounts={accounts} repository={repository} notify={setMessage}/>}
      {(module==='journals'||module==='opening-balances')&&<JournalCenter company={company} accounts={accounts} journals={journals} opening={module==='opening-balances'} repository={repository} reload={reload} notify={setMessage}/>}
      {module==='general-journal'&&<JournalList journals={journals} accounts={accounts}/>}
      {module==='ledger'&&<LedgerView company={company} accounts={accounts} repository={repository}/>}
      {module==='trial-balance'&&<TrialBalanceView rows={trial}/>}
      {module==='financial-statements'&&<StatementsView rows={trial}/>}
    </div></section></div></main>;
}

function PageHead({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:React.ReactNode}){return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold text-[#287C8E]">{eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#17324D]">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-[#6E8093]">{text}</p></div>{action}</div>}
function Notice({text,close}:{text:string;close:()=>void}){return <div className="mb-5 flex items-center justify-between rounded-xl border border-teal-200 bg-teal-50 p-4 text-sm font-bold text-teal-900"><span>{text}</span><button onClick={close}><X size={16}/></button></div>}
function Loading(){return <div className="grid min-h-screen place-items-center bg-[#F6F8FB]" dir="rtl"><div className="text-center"><div className="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-slate-200 border-t-[#287C8E]"/><p className="mt-3 text-sm font-bold">تحميل المحاسبة المحلية...</p></div></div>}

function AccountsView({company,accounts,repository,reload,notify}:{company:Company;accounts:Account[];repository:IndexedDBAccountingRepository;reload:()=>Promise<void>;notify:(x:string)=>void}) {
  const empty={code:'',arabicName:'',englishName:'',parentId:'',category:'asset' as AccountCategory,isPosting:true,projectRequired:false,costCenterRequired:false,costCodeRequired:false,currency:company.baseCurrency,status:'active' as Account['status']};
  const [form,setForm]=useState({...empty});
  const [editing,setEditing]=useState<string>();
  const [open,setOpen]=useState(false);
  const [search,setSearch]=useState('');
  const filtered=accounts.filter(a=>(a.code+' '+a.arabicName+' '+(a.englishName||'')).toLowerCase().includes(search.toLowerCase()));
  async function save(){try{await repository.saveAccount({...form,id:editing,companyId:company.id,parentId:form.parentId||undefined});setForm({...empty});setEditing(undefined);setOpen(false);notify('تم حفظ الحساب.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر الحفظ')}}
  function edit(a:Account){setEditing(a.id);setForm({code:a.code,arabicName:a.arabicName,englishName:a.englishName||'',parentId:a.parentId||'',category:a.category,isPosting:a.isPosting,projectRequired:a.projectRequired,costCenterRequired:a.costCenterRequired,costCodeRequired:a.costCodeRequired,currency:a.currency||company.baseCurrency,status:a.status});setOpen(true)}
  async function makeTemplate(){if(!confirm('إنشاء قالب حسابات مقاولات داخل الدليل الفارغ؟'))return;try{await repository.createContractingTemplate(company.id,company.baseCurrency);notify('تم إنشاء القالب بعد تأكيدك. يمكنك تعديله.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر إنشاء القالب')}}
  return <><PageHead eyebrow="Chart of Accounts" title="دليل الحسابات" text="دليل هرمي حقيقي. الحسابات التجميعية للعرض، وحسابات الترحيل فقط تقبل القيود." action={<div className="flex gap-2">{accounts.length===0&&<button onClick={makeTemplate} className="rounded-xl border border-[#287C8E] px-4 py-2.5 text-xs font-bold text-[#287C8E]">قالب مقاولات اختياري</button>}<button onClick={()=>{setForm({...empty});setEditing(undefined);setOpen(true)}} className="flex items-center gap-2 rounded-xl bg-[#287C8E] px-4 py-2.5 text-xs font-bold text-white"><Plus size={16}/>حساب جديد</button></div>}/>
  {open&&<section className="mb-6 rounded-2xl border border-[#DDE5EC] bg-white p-5"><h2 className="font-black">{editing?'تعديل الحساب':'إنشاء حساب'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="الكود *"><input className="field-input" dir="ltr" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></Field><Field label="الاسم العربي *"><input className="field-input" value={form.arabicName} onChange={e=>setForm({...form,arabicName:e.target.value})}/></Field><Field label="الاسم الإنجليزي"><input className="field-input" dir="ltr" value={form.englishName} onChange={e=>setForm({...form,englishName:e.target.value})}/></Field><Field label="التصنيف"><select className="field-input" value={form.category} onChange={e=>setForm({...form,category:e.target.value as AccountCategory})}>{Object.entries(categoryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="الحساب الأب"><select className="field-input" value={form.parentId} onChange={e=>setForm({...form,parentId:e.target.value})}><option value="">بدون</option>{accounts.filter(a=>a.id!==editing).map(a=><option key={a.id} value={a.id}>{a.code} — {a.arabicName}</option>)}</select></Field><Field label="العملة"><input className="field-input" dir="ltr" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/></Field></div><div className="mt-5 flex flex-wrap gap-4">{[['حساب ترحيل','isPosting'],['المشروع مطلوب','projectRequired'],['مركز التكلفة مطلوب','costCenterRequired'],['كود التكلفة مطلوب','costCodeRequired']].map(([label,key])=><label key={key} className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={Boolean(form[key as keyof typeof form])} onChange={e=>setForm({...form,[key]:e.target.checked})}/>{label}</label>)}</div><div className="mt-6 flex gap-2"><button onClick={save} className="flex items-center gap-2 rounded-xl bg-[#35A89A] px-5 py-2.5 text-xs font-bold text-white"><Save size={15}/>حفظ</button><button onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-5 py-2.5 text-xs font-bold">إلغاء</button></div></section>}
  <div className="mb-4 flex items-center gap-2 rounded-xl border border-[#DDE5EC] bg-white px-4"><Search size={17} className="text-slate-400"/><input className="w-full bg-transparent py-3 text-sm outline-none" placeholder="بحث بالكود أو الاسم" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  <section className="overflow-hidden rounded-2xl border border-[#DDE5EC] bg-white">
    {filtered.length===0?<Empty title="دليل الحسابات فارغ" text="أنشئ حسابًا يدويًا أو استخدم القالب الاختياري بعد تأكيدك."/>:<div className="overflow-x-auto"><table className="w-full min-w-[820px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">الكود</th><th>الحساب</th><th>التصنيف</th><th>النوع</th><th>المتطلبات</th><th>الحالة</th><th></th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(a=><tr key={a.id}><td className="p-4 font-mono font-bold">{a.code}</td><td><button onClick={()=>edit(a)} className="font-bold text-[#17324D] hover:text-[#287C8E]">{a.arabicName}</button><small className="block text-slate-400">{a.englishName}</small></td><td>{categoryLabels[a.category]}</td><td>{a.isPosting?'ترحيل':'تجميعي'}</td><td className="text-xs text-slate-500">{[a.projectRequired&&'مشروع',a.costCenterRequired&&'مركز تكلفة',a.costCodeRequired&&'كود تكلفة'].filter(Boolean).join(' · ')||'—'}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${a.status==='active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{a.status==='active'?'نشط':'متوقف'}</span></td><td><button onClick={async()=>{try{await repository.setAccountStatus(a.id,a.status==='active'?'inactive':'active');await reload();}catch(e){notify(e instanceof Error?e.message:'تعذر التعديل');}}} className="text-xs font-bold text-[#287C8E]">{a.status==='active'?'إيقاف':'تنشيط'}</button></td></tr>)}</tbody></table></div>}
  </section></>;
}

function MappingView({company,accounts,repository,notify}:{company:Company;accounts:Account[];repository:IndexedDBAccountingRepository;notify:(x:string)=>void}) {
  const [values,setValues]=useState<Partial<Record<AccountingMappingKey,string>>>({});
  useEffect(()=>{repository.listMappings(company.id).then(rows=>setValues(Object.fromEntries(rows.map(r=>[r.key,r.accountId]))));},[company.id,repository]);
  async function save(){try{await repository.saveMappings(company.id,values);notify('تم حفظ الربط المحاسبي بدون أي حسابات ثابتة.')}catch(e){notify(e instanceof Error?e.message:'تعذر الحفظ')}}
  const posting=accounts.filter(a=>a.isPosting&&a.status==='active');
  return <><PageHead eyebrow="Accounting Mapping" title="الربط المحاسبي" text="اربط كل غرض تشغيلي بحساب ترحيل نشط من دليل شركتك. يمكن استكمال الربط تدريجيًا." action={<button onClick={save} className="flex items-center gap-2 rounded-xl bg-[#287C8E] px-5 py-3 text-xs font-bold text-white"><Save size={16}/>حفظ الربط</button>}/>{posting.length===0?<Empty title="لا توجد حسابات ترحيل" text="أنشئ دليل الحسابات أولًا، ثم عد إلى هذه الشاشة." action="/erp/accounts"/>:<section className="grid gap-4 rounded-2xl border border-[#DDE5EC] bg-white p-5 sm:grid-cols-2 xl:grid-cols-3">{ACCOUNTING_MAPPING_KEYS.map(key=><Field key={key} label={ACCOUNTING_MAPPING_LABELS[key]}><select className="field-input" value={values[key]||''} onChange={e=>setValues({...values,[key]:e.target.value})}><option value="">غير مربوط</option>{posting.map(a=><option key={a.id} value={a.id}>{a.code} — {a.arabicName}</option>)}</select></Field>)}</section>}</>;
}

function JournalCenter({company,accounts,journals,opening,repository,reload,notify}:{company:Company;accounts:Account[];journals:JournalWithLines[];opening:boolean;repository:IndexedDBAccountingRepository;reload:()=>Promise<void>;notify:(x:string)=>void}) {
  const posting=accounts.filter(a=>a.isPosting&&a.status==='active');
  const blank=()=>({accountId:posting[0]?.id||'',description:'',debit:0,credit:0});
  const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [description,setDescription]=useState(opening?'قيد الأرصدة الافتتاحية':'');const [lines,setLines]=useState([blank(),blank()]);
  const totals=journalTotals(lines);
  const relevant=journals.filter(j=>opening?j.entry.sourceType==='opening_balance':j.entry.sourceType!=='opening_balance');
  async function save(){try{const draft:JournalDraft={companyId:company.id,date,description,sourceType:opening?'opening_balance':'manual',lines};await repository.saveJournal(draft);notify('تم حفظ القيد كمسودة. راجعه ثم اعتمده ورحّله.');setDescription(opening?'قيد الأرصدة الافتتاحية':'');setLines([blank(),blank()]);await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر حفظ القيد')}}
  async function action(kind:'approve'|'post'|'cancel'|'reverse',id:string){try{if(kind==='approve')await repository.approveJournal(id);if(kind==='post')await repository.postJournal(id);if(kind==='cancel')await repository.cancelJournal(id);if(kind==='reverse')await repository.reverseJournal(id,new Date().toISOString().slice(0,10));notify(kind==='post'?'تم ترحيل القيد بنجاح.':'تم تنفيذ الإجراء.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر تنفيذ الإجراء')}}
  return <><PageHead eyebrow={opening?'Opening Balance Center':'Journal Entries'} title={opening?'الأرصدة الافتتاحية':'القيود اليومية'} text={opening?'أدخل أرصدة الحسابات الحقيقية. لا يمكن ترحيل القيد إن لم يتساوَ المدين والدائن.':'أنشئ قيدًا، احفظه كمسودة، اعتمده، ثم رحّله. القيد المرحل لا يُعدل ويُعكس بقيد مقابل.'}/>
  {posting.length<2?<Empty title="الدليل غير جاهز للقيود" text="أنشئ حسابَي ترحيل نشطين على الأقل." action="/erp/accounts"/>:<section className="rounded-2xl border border-[#DDE5EC] bg-white p-5"><div className="grid gap-4 sm:grid-cols-[180px_1fr]"><Field label="التاريخ"><input type="date" className="field-input" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="الوصف"><input className="field-input" value={description} onChange={e=>setDescription(e.target.value)}/></Field></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[780px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">الحساب</th><th>البيان</th><th>مدين</th><th>دائن</th><th></th></tr></thead><tbody>{lines.map((line,i)=><tr key={i}><td className="p-2"><select className="field-input" value={line.accountId} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,accountId:e.target.value}:x))}>{posting.map(a=><option key={a.id} value={a.id}>{a.code} — {a.arabicName}</option>)}</select></td><td className="p-2"><input className="field-input" value={line.description} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/></td><td className="p-2"><input type="number" min="0" step=".01" className="field-input" value={line.debit||''} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,debit:Number(e.target.value),credit:e.target.value?0:x.credit}:x))}/></td><td className="p-2"><input type="number" min="0" step=".01" className="field-input" value={line.credit||''} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,credit:Number(e.target.value),debit:e.target.value?0:x.debit}:x))}/></td><td><button onClick={()=>lines.length>2&&setLines(lines.filter((_,n)=>n!==i))} className="text-red-500"><X size={16}/></button></td></tr>)}</tbody><tfoot><tr className="font-black"><td colSpan={2} className="p-3">الإجمالي</td><td>{totals.debit.toFixed(2)}</td><td>{totals.credit.toFixed(2)}</td><td></td></tr></tfoot></table></div><div className="mt-4 flex flex-wrap justify-between gap-3"><button onClick={()=>setLines([...lines,blank()])} className="flex items-center gap-1 rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold"><Plus size={14}/>سطر</button><button onClick={save} className="flex items-center gap-2 rounded-xl bg-[#287C8E] px-5 py-2.5 text-xs font-bold text-white"><Save size={15}/>حفظ مسودة</button></div></section>}
  <section className="mt-6 overflow-hidden rounded-2xl border border-[#DDE5EC] bg-white"><h2 className="border-b border-slate-100 p-5 font-black">القيود المسجلة</h2>{relevant.length===0?<Empty title="لا توجد قيود" text="أنشئ أول قيد من النموذج أعلاه."/>:<div className="divide-y divide-slate-100">{relevant.map(j=><div key={j.entry.id} className="flex flex-col justify-between gap-3 p-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><strong>{j.entry.number}</strong><Status value={j.entry.status}/></div><p className="mt-1 text-sm text-slate-600">{j.entry.description}</p><p className="mt-1 text-xs text-slate-400">{j.entry.date} · مدين {journalTotals(j.lines).debit.toFixed(2)} · دائن {journalTotals(j.lines).credit.toFixed(2)}</p></div><div className="flex flex-wrap gap-2">{j.entry.status==='draft'&&<button onClick={()=>action('approve',j.entry.id)} className="action-btn"><Check size={14}/>اعتماد</button>}{j.entry.status==='approved'&&<button onClick={()=>action('post',j.entry.id)} className="action-btn"><Send size={14}/>ترحيل</button>}{j.entry.status==='posted'&&<button onClick={()=>action('reverse',j.entry.id)} className="action-btn"><RotateCcw size={14}/>عكس</button>}{['draft','approved'].includes(j.entry.status)&&<button onClick={()=>action('cancel',j.entry.id)} className="action-btn text-red-600"><X size={14}/>إلغاء</button>}</div></div>)}</div>}</section></>;
}

function JournalList({journals,accounts}:{journals:JournalWithLines[];accounts:Account[]}) {
  const [search,setSearch]=useState('');const names=new Map(accounts.map(a=>[a.id,a.code+' — '+a.arabicName]));const rows=journals.filter(j=>(j.entry.number+' '+j.entry.description).toLowerCase().includes(search.toLowerCase()));
  return <><PageHead eyebrow="General Journal" title="اليومية العامة" text="قائمة كل القيود المحلية مع حالة المستند وسطور الحسابات الحقيقية."/><div className="mb-4 flex items-center gap-2 rounded-xl border border-[#DDE5EC] bg-white px-4"><Search size={16}/><input className="w-full py-3 outline-none" placeholder="بحث برقم أو وصف القيد" value={search} onChange={e=>setSearch(e.target.value)}/></div><section className="space-y-3">{rows.length===0?<Empty title="لا توجد قيود مطابقة" text="أنشئ قيدًا من مركز القيود." action="/erp/journals"/>:rows.map(j=><details key={j.entry.id} className="rounded-2xl border border-[#DDE5EC] bg-white p-5"><summary className="flex cursor-pointer list-none flex-wrap items-center gap-3"><strong>{j.entry.number}</strong><Status value={j.entry.status}/><span className="text-sm text-slate-600">{j.entry.description}</span><span className="mr-auto text-xs text-slate-400">{j.entry.date}</span></summary><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">الحساب</th><th>البيان</th><th>مدين</th><th>دائن</th></tr></thead><tbody>{j.lines.map(l=><tr key={l.id} className="border-t border-slate-100"><td className="p-3">{names.get(l.accountId)}</td><td>{l.description||'—'}</td><td>{l.debit.toFixed(2)}</td><td>{l.credit.toFixed(2)}</td></tr>)}</tbody></table></div></details>)}</section></>;
}

function LedgerView({company,accounts,repository}:{company:Company;accounts:Account[];repository:IndexedDBAccountingRepository}) {
  const posting=accounts.filter(a=>a.isPosting);const [accountId,setAccountId]=useState(posting[0]?.id||'');const [rows,setRows]=useState<LedgerRow[]>([]);
  useEffect(()=>{if(accountId)repository.getLedger(company.id,accountId).then(setRows)},[accountId,company.id,repository]);
  return <><PageHead eyebrow="General Ledger" title="الأستاذ العام" text="الحركة والرصيد الجاري مشتقان من القيود المرحلة فقط، مع رابط للقيد المصدر."/><Field label="الحساب"><select className="field-input max-w-xl" value={accountId} onChange={e=>setAccountId(e.target.value)}>{posting.map(a=><option key={a.id} value={a.id}>{a.code} — {a.arabicName}</option>)}</select></Field><section className="mt-5 overflow-hidden rounded-2xl border border-[#DDE5EC] bg-white">{rows.length===0?<Empty title="لا توجد حركة مرحلة" text="رحّل قيدًا يحتوي هذا الحساب لظهوره في الأستاذ."/>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">التاريخ</th><th>القيد</th><th>البيان</th><th>مدين</th><th>دائن</th><th>الرصيد</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.journalId+'-'+i} className="border-t border-slate-100"><td className="p-4">{r.date}</td><td><Link className="font-bold text-[#287C8E]" href="/erp/general-journal">{r.journalNumber}</Link></td><td>{r.description}</td><td>{r.debit.toFixed(2)}</td><td>{r.credit.toFixed(2)}</td><td className="font-black">{r.runningBalance.toFixed(2)}</td></tr>)}</tbody></table></div>}</section></>;
}

function TrialBalanceView({rows}:{rows:TrialBalanceRow[]}) { const shown=rows.filter(r=>r.debitMovement||r.creditMovement);const td=shown.reduce((s,r)=>s+r.debitBalance,0);const tc=shown.reduce((s,r)=>s+r.creditBalance,0);return <><PageHead eyebrow="Trial Balance" title="ميزان المراجعة" text="يُحتسب من القيود المرحلة فقط، ويجب أن يتساوى إجمالي الأرصدة المدينة والدائنة."/><section className="overflow-hidden rounded-2xl border border-[#DDE5EC] bg-white">{shown.length===0?<Empty title="لا توجد أرصدة مرحلة" text="بعد ترحيل القيود سيظهر ميزان المراجعة هنا."/>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">الحساب</th><th>حركة مدين</th><th>حركة دائن</th><th>رصيد مدين</th><th>رصيد دائن</th></tr></thead><tbody>{shown.map(r=><tr key={r.accountId} className="border-t border-slate-100"><td className="p-4 font-bold">{r.accountCode} — {r.accountName}</td><td>{r.debitMovement.toFixed(2)}</td><td>{r.creditMovement.toFixed(2)}</td><td>{r.debitBalance.toFixed(2)}</td><td>{r.creditBalance.toFixed(2)}</td></tr>)}</tbody><tfoot className="bg-[#17324D] font-black text-white"><tr><td className="p-4">الإجمالي</td><td></td><td></td><td>{td.toFixed(2)}</td><td>{tc.toFixed(2)}</td></tr></tfoot></table></div>}</section><div className={`mt-4 rounded-xl p-4 text-sm font-bold ${Math.abs(td-tc)<.01?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-800'}`}>{Math.abs(td-tc)<.01?'ميزان المراجعة متوازن.':'تحذير: ميزان المراجعة غير متوازن.'}</div></>}

function StatementsView({rows}:{rows:TrialBalanceRow[]}) {const s=buildFinancialStatements(rows);return <><PageHead eyebrow="Financial Statements" title="القوائم المالية" text="قائمة الدخل والميزانية مشتقتان من ميزان المراجعة المحلي. لا توجد أرقام افتراضية."/><div className="grid gap-6 xl:grid-cols-2"><Statement title="قائمة الدخل" groups={[['الإيرادات',s.revenue,'credit'],['المصروفات',s.expenses,'debit']]} footer={['صافي الربح / الخسارة',s.netIncome]}/><Statement title="قائمة المركز المالي" groups={[['الأصول',s.assets,'debit'],['الالتزامات',s.liabilities,'credit'],['حقوق الملكية',s.equity,'credit']]} footer={['الأصول',s.totalAssets]}/></div><div className={`mt-5 rounded-xl p-4 text-sm font-bold ${Math.abs(s.totalAssets-s.totalLiabilitiesAndEquity)<.01?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-900'}`}>الأصول {s.totalAssets.toFixed(2)} · الالتزامات وحقوق الملكية وصافي النتيجة {s.totalLiabilitiesAndEquity.toFixed(2)} — {Math.abs(s.totalAssets-s.totalLiabilitiesAndEquity)<.01?'الميزانية متوازنة':'تحتاج مراجعة تصنيف الحسابات أو الأرصدة'}</div></>}
function Statement({title,groups,footer}:{title:string;groups:[string,TrialBalanceRow[],string][];footer:[string,number]}){return <section className="rounded-2xl border border-[#DDE5EC] bg-white p-5"><h2 className="text-xl font-black text-[#17324D]">{title}</h2>{groups.map(([name,rows,side])=><div key={name} className="mt-5"><h3 className="mb-2 text-xs font-black text-[#287C8E]">{name}</h3>{rows.filter(r=>r.debitBalance||r.creditBalance).map(r=><div key={r.accountId} className="flex justify-between border-b border-slate-100 py-2 text-sm"><span>{r.accountCode} — {r.accountName}</span><strong>{(side==='debit'?r.debitBalance-r.creditBalance:r.creditBalance-r.debitBalance).toFixed(2)}</strong></div>)}</div>)}<div className="mt-5 flex justify-between rounded-xl bg-[#17324D] p-4 font-black text-white"><span>{footer[0]}</span><span>{footer[1].toFixed(2)}</span></div></section>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field-label">{label}{children}</label>}
function Empty({title,text,action}:{title:string;text:string;action?:string}){return <div className="p-10 text-center"><CircleDollarSign className="mx-auto text-slate-300"/><h3 className="mt-3 font-black text-[#17324D]">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{text}</p>{action&&<Link href={action} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#287C8E] px-4 py-2.5 text-xs font-bold text-white">فتح الخطوة المطلوبة<ArrowLeft size={14}/></Link>}</div>}
function Status({value}:{value:keyof typeof statusLabels}){return <span className={`rounded-full px-2 py-1 text-[9px] font-bold ${value==='posted'?'bg-emerald-50 text-emerald-700':value==='cancelled'||value==='reversed'?'bg-red-50 text-red-700':'bg-blue-50 text-blue-700'}`}>{statusLabels[value]}</span>}
