import Link from 'next/link';
import { AlertTriangle, ArrowLeft, BarChart3, BookOpen, Building2, Calculator, Check, CheckCircle2, ClipboardCheck, Database, FileCheck2, GitBranch, HardHat, HelpCircle, PieChart, ReceiptText, SearchCheck, ShoppingCart, TrendingUp, WalletCards, Warehouse, Workflow } from 'lucide-react';

const workflow = ['المناقصة','العقد','المشروع','BOQ','Budget','المشتريات','الموردين','المخازن','تحويل الموقع','استهلاك الخامات','مقاولو الباطن','المستخلصات','التحصيل','الحسابات','التقارير','ربحية المشروع'];
const problems = ['تكاليف المشروع موزعة بين ملفات مختلفة','الموردون منفصلون عن الحسابات','المخزون غير مرتبط بالتكلفة الفعلية','المستخلصات منفصلة عن التحصيل','صعوبة معرفة الربح الحقيقي لكل مشروع','عدم وضوح الالتزامات القادمة'];
const accountingFeatures = ['دليل حسابات متعدد المستويات','قيود تلقائية ويدوية','الأستاذ العام والمساعد','ميزان المراجعة','التسويات والمطابقات','المستحقات والمقدمات','الإهلاك','الإقفال الشهري والسنوي','قائمة الدخل والميزانية','التدفقات النقدية'];
const industries = ['شركات المقاولات الصناعية','MEP','أعمال الكهرباء','أعمال الميكانيكا','Steel Structure','Piping','Fire Fighting','Factory Installation','Industrial Maintenance'];

export function MarketingSections({cta}:{cta:string}) {
  return <>
    <section id="features" className="bg-white py-20 lg:py-28">
      <Container>
        <div className="grid items-center gap-12 lg:grid-cols-2">
          <div><Eyebrow>المشكلة والحل</Eyebrow><h2 className="section-title">المشكلة مش في إنك تعرف صرفت كام...<span>المشكلة إنك تعرف صرفت فين وليه</span></h2><p className="section-copy">المنظومة تربط كل حركة تشغيلية بأثرها المالي والمحاسبي مباشرة، فتظهر الصورة قبل أن تتحول الفجوة إلى خسارة.</p></div>
          <div className="grid gap-3 sm:grid-cols-2">{problems.map((item,i)=><div key={item} className="group flex gap-3 rounded-2xl border border-slate-200 bg-[#fbfdff] p-4 transition hover:-translate-y-1 hover:border-teal-200 hover:shadow-lg"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-red-50 text-xs font-black text-red-600">{String(i+1).padStart(2,'0')}</span><p className="text-sm font-bold leading-6 text-slate-700">{item}</p></div>)}</div>
        </div>
        <div className="mt-12 rounded-[28px] border border-teal-200 bg-gradient-to-l from-teal-50 to-blue-50 p-6 sm:p-8"><div className="flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-center"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#16836f] text-white"><Workflow/></span><div><h3 className="font-black text-[#0c3156]">تشغيل واحد. أثر مالي واحد. مصدر واحد للحقيقة.</h3><p className="mt-2 text-sm leading-7 text-slate-600">المشتريات والمخزون والمستخلصات والخزينة لا تعمل كجزر منفصلة عن الحسابات وتكلفة المشروع.</p></div></div><span className="rounded-full bg-white px-4 py-2 text-xs font-bold text-[#16836f] shadow-sm">Integrated by design</span></div></div>
      </Container>
    </section>

    <section id="workflow" className="py-20 lg:py-28"><Container><SectionHead eyebrow="الدورة التشغيلية" title="دورة المشروع كاملة في نظام واحد" text="من فرصة البيع حتى ربحية المشروع، كل مرحلة تسلّم المرحلة التالية مستندًا واضحًا وأثرًا قابلًا للتتبع."/><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{workflow.map((item,i)=><div key={item} className="relative flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#0c3156] text-[11px] font-black text-white">{i+1}</span><strong className="text-sm text-slate-700">{item}</strong>{i<workflow.length-1&&<ArrowLeft size={14} className="absolute -left-2.5 z-10 hidden rounded-full bg-[#22a58b] p-0.5 text-white lg:block"/>}</div>)}</div></Container></section>

    <section id="projects" className="bg-[#0b2d4d] py-20 text-white lg:py-28"><Container><SectionHead light eyebrow="إدارة المشروع" title="مش بس إدارة مشروع... إدارة تكلفة وربحية المشروع" text="افصل بين قيمة العقد والميزانية والتكلفة والالتزام والسيولة، واتخذ القرار على رقم مفهوم ومصدر واضح."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[
      ['العقد',['Original Contract','Approved Variations','Revised Contract Value'],Building2],['الميزانية',['Original Budget','Current Budget','Budget Variance'],Calculator],['التكلفة',['Actual Cost','Committed Cost','Forecast Cost'],WalletCards],['الربحية',['Expected Profit','Margin','Cash Position'],TrendingUp],['التقدم',['Physical Progress','Cost Progress','Project Risk'],BarChart3],
    ].map(([title,items,Icon])=>{const ProjectIcon=Icon as typeof Building2;return <article key={title as string} className="rounded-2xl border border-white/10 bg-white/7 p-5 backdrop-blur-sm"><ProjectIcon className="text-[#55d8c0]"/><h3 className="mt-5 font-extrabold">{title as string}</h3><ul className="mt-4 space-y-2">{(items as string[]).map(i=><li key={i} className="text-[11px] text-blue-100/65">{i}</li>)}</ul></article>})}</div>
      <div className="mt-8 grid items-center gap-8 rounded-[28px] border border-white/10 bg-white/5 p-6 sm:p-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold text-[#55d8c0]">هيكل مشروع صناعي احترافي</p><h3 className="mt-3 text-2xl font-black">كل جنيه له مكان داخل هيكل التكلفة</h3><p className="mt-3 text-sm leading-7 text-blue-100/65">اعرف اتصرف على أي مشروع، وأي منطقة، وأي نظام، وأي Work Package، وأي BOQ Item، وأي Cost Code.</p></div><div className="flex flex-wrap items-center gap-2 text-xs font-bold">{['مصنع أكتوبر','منطقة الإنتاج','Fire Fighting','Piping Works','Carbon Steel Pipe','MAT-PIPE'].map((item,i)=><span key={item} className="flex items-center gap-2"><span className={`rounded-xl px-3 py-2.5 ${i===5?'bg-[#22a58b] text-white':'bg-white/10 text-blue-50'}`}>{item}</span>{i<5&&<ArrowLeft size={13} className="text-[#55d8c0]"/>}</span>)}</div></div>
    </Container></section>

    <section id="accounting" className="bg-white py-20 lg:py-28"><Container><SectionHead eyebrow="المحاسبة" title="دورة محاسبية كاملة... مش مجرد تقارير" text="كل عملية تشغيلية لها أثر محاسبي واضح وقابل للتتبع، من المستند الأصلي إلى القوائم والإقفال."/><ProcessFlow items={['المستند','القيد','اليومية','الأستاذ','ميزان المراجعة','التسويات','القوائم المالية','الإقفال']}/><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{accountingFeatures.map((item)=><div key={item} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><CheckCircle2 size={17} className="shrink-0 text-[#16836f]"/><span className="text-xs font-bold text-slate-700">{item}</span></div>)}</div>
      <div className="mt-12 grid overflow-hidden rounded-[30px] border border-slate-200 bg-[#f7fafc] shadow-[0_24px_70px_rgba(12,49,86,.08)] lg:grid-cols-2"><div className="p-7 sm:p-10"><Eyebrow>Accounting Impact Preview</Eyebrow><h3 className="text-2xl font-black text-[#0c3156]">فاتورة مورد قبل الترحيل</h3><div className="mt-7 space-y-3"><AmountRow label="خامات" value="100,000"/><AmountRow label="VAT Input" value="14,000"/><AmountRow label="الإجمالي" value="114,000" strong/></div><p className="mt-6 text-[11px] leading-6 text-slate-400">مثال تسويقي فقط — لا ينشئ فاتورة أو قيدًا ولا يكتب أي بيانات في IndexedDB.</p></div><div className="bg-[#0c3156] p-7 text-white sm:p-10"><p className="text-xs font-bold text-[#55d8c0]">القيد المتوقع</p><div className="mt-6 space-y-4 font-mono text-sm" dir="ltr"><EntryRow left="Dr Inventory" right="100,000"/><EntryRow left="Dr VAT Input" right="14,000"/><EntryRow left="Cr Supplier" right="114,000" accent/></div><div className="mt-8 flex flex-wrap items-center gap-2 text-[10px] text-blue-100/70" dir="rtl">{['فاتورة المورد','المخزون','حساب المورد','القيد','الأستاذ'].map((x,i)=><span key={x} className="flex items-center gap-2"><span className="rounded-lg bg-white/10 px-2.5 py-2">{x}</span>{i<4&&<ArrowLeft size={12}/>}</span>)}</div></div></div>
    </Container></section>

    <section className="py-20 lg:py-28"><Container><div className="grid gap-6 lg:grid-cols-2"><ModulePanel icon={<ShoppingCart/>} eyebrow="المشتريات" title="دورة مشتريات حقيقية" flow={['طلب شراء','RFQ','عروض','مقارنة','أمر شراء','استلام','فاتورة','سداد']} features={['مقارنة الموردين','مواعيد التوريد','Purchase Commitments','Three-Way Matching','PO vs GRN vs Invoice','Supplier Aging']}/><ModulePanel icon={<Warehouse/>} eyebrow="المخازن" title="اعرف الخامة فين... واتكلفت على إيه" flow={['المورد','المخزن الرئيسي','مخزن الموقع','Material Issue','المشروع']} features={['Multi-Warehouse','Transfers','Material Returns','Waste','Weighted Average Cost','Stock Ledger']}/></div><div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-center text-sm font-extrabold text-amber-900">نقل الخامة للموقع لا يعني استهلاكها — التكلفة الفعلية تبدأ عند Material Issue.</div></Container></section>

    <section className="bg-white py-20 lg:py-28"><Container><div className="grid gap-8 lg:grid-cols-2"><TextVisual eyebrow="مقاولو الباطن" title="مقاولو الباطن تحت السيطرة" text="العقد، BOQ، الدفعة المقدمة، الاستقطاعات، Retention، المستخلص، الدفع، والرصيد في مسار واحد." items={['Subcontract','Progress','Certificate','Deductions','Payable','Payment']} icon={<HardHat/>}/><TextVisual eyebrow="مستخلصات العملاء" title="من التنفيذ للتحصيل" text="اعرف عملت مستخلص بكام، اتحصل منه كام، والمتبقي عند العميل كام، مع فصل الاحتجاز واسترداد الدفعة المقدمة والضريبة." items={['BOQ','Current Work','IPC','Retention','Receivable','Collection']} icon={<FileCheck2/>}/></div></Container></section>

    <section className="py-20 lg:py-28"><Container><div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="rounded-[28px] bg-[#0c3156] p-7 text-white sm:p-9"><p className="text-xs font-bold text-[#55d8c0]">Cash Flow</p><h2 className="mt-4 text-3xl font-black">الربح مش هو السيولة</h2><p className="mt-4 text-sm leading-8 text-blue-100/70">ممكن المشروع يكون رابح، لكن الشركة تعاني من عجز سيولة بسبب تأخر التحصيلات أو ضغط المدفوعات.</p><div className="mt-8 grid grid-cols-2 gap-3"><CashBox label="Project Profit" value="+8.7M" good/><CashBox label="Cash Position" value="-1.2M"/></div></div><ProfitabilityMock/></div></Container></section>

    <section className="bg-white py-20 lg:py-28"><Container><SectionHead eyebrow="الإنذار المبكر" title="المشكلة تظهر قبل ما تتحول لخسارة" text="المؤشرات التشغيلية والمالية تعمل معًا لإظهار الانحراف مبكرًا."/><div className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[28px] border border-red-200 bg-red-50 p-7"><div className="flex items-center gap-3 text-red-700"><AlertTriangle/><strong>خطر تجاوز التكلفة</strong></div><div className="mt-8 grid grid-cols-2 gap-5"><Progress label="Physical Progress" value={60} color="bg-[#0c5f8f]"/><Progress label="Budget Consumed" value={92} color="bg-red-500"/></div><p className="mt-6 text-sm font-bold text-red-800">الاستهلاك المالي يسبق التقدم الفعلي بـ32 نقطة.</p></div><div className="grid grid-cols-2 gap-3">{['تأخر مستخلص عميل','مورد مستحق','خامة قاربت على النفاد','زيادة هالك','انخفاض هامش مشروع','شيك قريب','ضمان بنكي قرب ينتهي','تأخر توريد'].map(x=><div key={x} className="rounded-xl border border-slate-200 p-4 text-xs font-bold text-slate-700">{x}</div>)}</div></div></Container></section>

    <section id="dashboards" className="py-20 lg:py-28"><Container><SectionHead eyebrow="لوحات الإدارة" title="كل مسؤول يشوف القرار اللي يخصه" text="لوحات مركزة لا تخلط بين دور المالك والمحاسب ومدير المشروع والمشتريات."/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><RoleCard title="Owner Dashboard" icon={<Building2/>} items={['Cash','Receivables','Payables','Project Profit','Risk','Collections']}/><RoleCard title="Accountant Dashboard" icon={<BookOpen/>} items={['Trial Balance','Unposted','Reconciliations','Closing','VAT']}/><RoleCard title="Project Manager" icon={<HardHat/>} items={['Budget','Actual','Committed','Forecast','Progress','Risk']}/><RoleCard title="Procurement" icon={<ShoppingCart/>} items={['Open PR','RFQ','PO','Late Deliveries']}/></div>
      <div className="mt-10 rounded-[28px] border border-slate-200 bg-white p-7 shadow-sm"><div className="grid items-center gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><Eyebrow>Full Traceability</Eyebrow><h3 className="text-2xl font-black text-[#0c3156]">من رقم في الـDashboard لحد المستند الأصلي</h3><p className="mt-3 text-sm leading-7 text-slate-600">كل رقم في النظام لازم يكون له مصدر، ومسار يمكن مراجعته دون تخمين.</p></div><ProcessFlow compact items={['Dashboard KPI','Report','Transaction','Source Document','Journal Entry','General Ledger']}/></div></div>
    </Container></section>

    <section className="bg-[#eaf6f4] py-20 lg:py-28"><Container><div className="grid items-center gap-10 lg:grid-cols-2"><div><Eyebrow>Frontend-Only Trial Edition</Eyebrow><h2 className="section-title">جرّب النظام بنفسك<span>وابنِ بيئتك من صفحة نظيفة</span></h2><p className="section-copy">لا قاعدة بيانات خارجية، لا اشتراك، لا API، ولا بيانات افتراضية. أدخل شركتك ومشروعاتك بنفسك وأنشئ Backup محليًا.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['لا شركات وهمية','لا أرصدة مصطنعة','لا مشروعات افتراضية','لا فواتير تلقائية','بياناتك في متصفحك','Backup واستعادة'].map(x=><div key={x} className="flex items-center gap-2 text-sm font-bold text-slate-700"><Check size={16} className="text-[#16836f]"/>{x}</div>)}</div><Link href="/setup" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-[#0c5f8f] px-7 py-4 text-sm font-black text-white">{cta}<ArrowLeft size={17}/></Link></div><div className="rounded-[30px] border border-white/80 bg-white/75 p-7 shadow-xl backdrop-blur"><div className="flex items-center gap-3"><Database className="text-[#16836f]"/><h3 className="font-black text-[#0c3156]">حدود النسخة التجريبية واضحة</h3></div><p className="mt-4 text-sm leading-8 text-slate-600">التخزين المحلي مناسب للتجربة الفردية على نفس الجهاز، وليس تشغيلًا إنتاجيًا متعدد المستخدمين.</p><div className="my-6 h-px bg-slate-200"/><p className="text-sm font-bold leading-8 text-[#0c3156]">عند اعتماد النظام داخل الشركة يتم تجهيز النسخة الإنتاجية وربط Backend وقاعدة بيانات مركزية حسب احتياجات الشركة.</p></div></div></Container></section>

    <section className="bg-white py-20 lg:py-28"><Container><div className="grid gap-10 lg:grid-cols-2"><div><Eyebrow>تجربة موجهة</Eyebrow><h2 className="section-title">مش هنسيبك تتوه جوه النظام</h2><div className="mt-8 grid gap-3 sm:grid-cols-2">{[['Setup Wizard',ClipboardCheck],['Workflow Center',Workflow],['Context Help',HelpCircle],['Accounting Impact',ReceiptText],['Step-by-Step Guide',GitBranch],['Empty State Guidance',SearchCheck]].map(([x,Icon])=><div key={x as string} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><Icon className="text-[#16836f]" size={19}/><strong className="text-sm text-slate-700">{x as string}</strong></div>)}</div></div><div><Eyebrow>مناسب لمين؟</Eyebrow><h2 className="section-title">للشركات اللي شغلها مشروع وتكلفة ومسؤولية</h2><div className="mt-8 flex flex-wrap gap-3">{industries.map(x=><span key={x} className="rounded-full border border-slate-200 bg-slate-50 px-4 py-2.5 text-xs font-bold text-slate-700">{x}</span>)}</div></div></div></Container></section>

    <section className="py-20 lg:py-28"><Container><SectionHead eyebrow="لماذا هذه المنظومة؟" title="بدل أدوات منفصلة... نظام واحد متمركز حول المشروع"/><div className="mt-10 grid overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-xl lg:grid-cols-2"><Comparison bad title="الأدوات المنفصلة" items={['Excel متفرق','برنامج حسابات منفصل','مخزن يدوي','شيتات مشروعات','اعتمادات WhatsApp']}/><Comparison title="Industrial Contracting ERP" items={['Integrated','Traceable','Project-Centered','Accounting-Driven','Cost-Controlled']}/></div></Container></section>

    <section id="faq" className="bg-white py-20 lg:py-28"><Container><SectionHead eyebrow="الأسئلة الشائعة" title="قبل ما تبدأ التجربة"/><div className="mx-auto mt-10 max-w-4xl divide-y divide-slate-200 rounded-[24px] border border-slate-200 px-6">{[
      ['هل أحتاج قاعدة بيانات أو اشتراك؟','لا. النسخة الحالية تعمل داخل المتصفح وتستخدم IndexedDB محليًا.'],['هل توجد بيانات افتراضية؟','لا. تبدأ من الصفر وتنشئ شركتك وبياناتك بنفسك.'],['هل التخزين المحلي مناسب للإنتاج؟','لا. هو مخصص للتجربة الفردية؛ النسخة الإنتاجية تحتاج Backend وقاعدة مركزية وصلاحيات حقيقية.'],['هل بياناتي الحالية ستضيع عند زيارة الصفحة؟','لا. صفحة الهبوط لا تعدّل قاعدة البيانات، وزر فتح النظام يعيدك إلى بيئتك المحلية كما هي.'],
    ].map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-extrabold text-[#0c3156]"><span>{q}</span><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-100 text-lg group-open:rotate-45">+</span></summary><p className="mt-3 text-sm leading-7 text-slate-600">{a}</p></details>)}</div></Container></section>

    <section className="px-5 py-16 lg:px-10"><div className="mx-auto max-w-[1360px] overflow-hidden rounded-[34px] bg-[#0b3153] px-6 py-14 text-center text-white shadow-[0_35px_90px_rgba(12,49,86,.2)] sm:px-10 lg:py-20"><p className="text-xs font-bold text-[#55d8c0]">ابدأ من بياناتك أنت</p><h2 className="mx-auto mt-4 max-w-4xl text-3xl font-black leading-tight sm:text-4xl lg:text-5xl">جاهز تشوف مشروعك من أول العقد لحد آخر رقم في القوائم المالية؟</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-blue-100/70">ابدأ نسخة التجربة، أنشئ شركتك بنفسك، وجرب الدورة المتاحة خطوة بخطوة.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/setup" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#29b39e] px-8 py-4 text-sm font-black text-white">{cta}<ArrowLeft size={18}/></Link><Link href="#features" className="rounded-2xl border border-white/15 bg-white/5 px-8 py-4 text-sm font-black">استعرض المميزات</Link></div></div></section>

    <footer className="border-t border-slate-200 bg-white"><Container><div className="grid gap-10 py-12 lg:grid-cols-[1.2fr_2fr]"><div><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#0c5f8f] font-black text-white">م</span><div><strong className="block text-[#0c3156]">منظومة المقاولات</strong><small className="text-slate-400">Industrial Contracting ERP</small></div></div><p className="mt-4 max-w-sm text-xs leading-6 text-slate-500">Frontend-Only Trial Edition. بيانات التجربة محفوظة محليًا على نفس المتصفح والجهاز.</p></div><div className="grid grid-cols-2 gap-4 text-xs font-bold text-slate-600 sm:grid-cols-4">{[['المميزات','#features'],['الدورة المحاسبية','#accounting'],['المشروعات','#projects'],['المشتريات','#workflow'],['المخازن','#workflow'],['التقارير','#dashboards'],['ابدأ التجربة','/setup']].map(([x,h])=><Link key={x} href={h} className="hover:text-[#16836f]">{x}</Link>)}</div></div><div className="border-t border-slate-100 py-5 text-center text-[10px] text-slate-400">منظومة تجريبية محلية — لا تمثل نظام دخول أو تشغيلًا إنتاجيًا متعدد المستخدمين.</div></Container></footer>
  </>;
}

function Container({children}:{children:React.ReactNode}){return <div className="mx-auto max-w-[1360px] px-5 lg:px-10">{children}</div>}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="mb-3 text-xs font-extrabold text-[#16836f]">{children}</p>}
function SectionHead({eyebrow,title,text,light=false}:{eyebrow:string;title:string;text?:string;light?:boolean}){return <div className="mx-auto max-w-3xl text-center"><Eyebrow>{eyebrow}</Eyebrow><h2 className={`text-3xl font-black tracking-tight sm:text-4xl ${light?'text-white':'text-[#0c3156]'}`}>{title}</h2>{text&&<p className={`mt-4 text-sm leading-7 ${light?'text-blue-100/65':'text-slate-600'}`}>{text}</p>}</div>}
function ProcessFlow({items,compact=false}:{items:string[];compact?:boolean}){return <div className={`mt-10 flex flex-col gap-2 ${compact?'lg:mt-0':'sm:flex-row sm:flex-wrap sm:justify-center'}`}>{items.map((item,i)=><span key={item} className="flex items-center gap-2"><span className="whitespace-nowrap rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-bold text-slate-700">{item}</span>{i<items.length-1&&<ArrowLeft size={13} className="hidden text-[#16836f] sm:block"/>}</span>)}</div>}
function AmountRow({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={`flex items-center justify-between rounded-xl px-4 py-3 ${strong?'bg-[#0c3156] text-white':'border border-slate-200 bg-white'}`}><span className="text-sm font-bold">{label}</span><strong>{value}</strong></div>}
function EntryRow({left,right,accent=false}:{left:string;right:string;accent?:boolean}){return <div className={`flex justify-between rounded-xl px-4 py-3 ${accent?'bg-[#22a58b]':'bg-white/7'}`}><span>{left}</span><strong>{right}</strong></div>}
function ModulePanel({icon,eyebrow,title,flow,features}:{icon:React.ReactNode;eyebrow:string;title:string;flow:string[];features:string[]}){return <article className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-[#0c5f8f]">{icon}</span><div><p className="text-xs font-bold text-[#16836f]">{eyebrow}</p><h3 className="mt-1 text-xl font-black text-[#0c3156]">{title}</h3></div></div><div className="mt-7 flex flex-wrap gap-2">{flow.map((x,i)=><span key={x} className="flex items-center gap-2"><span className="rounded-lg bg-slate-100 px-2.5 py-2 text-[10px] font-bold">{x}</span>{i<flow.length-1&&<ArrowLeft size={11} className="text-[#16836f]"/>}</span>)}</div><div className="mt-7 grid grid-cols-2 gap-2">{features.map(x=><div key={x} className="flex items-center gap-2 text-[11px] font-bold text-slate-600"><Check size={13} className="text-[#16836f]"/>{x}</div>)}</div></article>}
function TextVisual({eyebrow,title,text,items,icon}:{eyebrow:string;title:string;text:string;items:string[];icon:React.ReactNode}){return <article className="rounded-[28px] border border-slate-200 p-7 sm:p-9"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-[#16836f]">{icon}</span><p className="mt-6 text-xs font-bold text-[#16836f]">{eyebrow}</p><h3 className="mt-2 text-2xl font-black text-[#0c3156]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p><div className="mt-6 flex flex-wrap gap-2">{items.map((x,i)=><span key={x} className="flex items-center gap-2"><span className="rounded-lg bg-slate-100 px-2.5 py-2 text-[10px] font-bold">{x}</span>{i<items.length-1&&<ArrowLeft size={11} className="text-[#16836f]"/>}</span>)}</div></article>}
function CashBox({label,value,good=false}:{label:string;value:string;good?:boolean}){return <div className={`rounded-xl p-4 ${good?'bg-emerald-400/15':'bg-red-400/15'}`}><p className="text-[10px] text-blue-100/60">{label}</p><strong className={`mt-2 block text-xl ${good?'text-emerald-300':'text-red-300'}`}>{value}</strong></div>}
function ProfitabilityMock(){const metrics=['Contract Value','Approved Variations','Current Budget','Actual Cost','Committed Cost','Forecast Cost','Certified Revenue','Collected Cash','Expected Profit','Margin','Cash Position'];return <div className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[#16836f]">Project Profitability</p><h3 className="mt-1 font-black text-[#0c3156]">صورة واحدة لا تخلط بين المؤشرات</h3></div><PieChart className="text-[#0c5f8f]"/></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{metrics.map((x,i)=><div key={x} className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-bold text-slate-400">{x}</p><div className="mt-3 h-2 rounded-full bg-slate-200"><div className={`h-full rounded-full ${i>7?'bg-[#22a58b]':'bg-[#0c5f8f]'}`} style={{width:`${38+(i*7)%55}%`}}/></div></div>)}</div></div>}
function Progress({label,value,color}:{label:string;value:number;color:string}){return <div><div className="flex justify-between text-xs font-bold"><span>{label}</span><span>{value}%</span></div><div className="mt-3 h-3 rounded-full bg-white"><div className={`h-full rounded-full ${color}`} style={{width:`${value}%`}}/></div></div>}
function RoleCard({title,icon,items}:{title:string;icon:React.ReactNode;items:string[]}){return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-[#0c5f8f]">{icon}</span><h3 className="mt-5 font-black text-[#0c3156]">{title}</h3><div className="mt-4 flex flex-wrap gap-2">{items.map(x=><span key={x} className="rounded-full bg-slate-100 px-2.5 py-1.5 text-[9px] font-bold text-slate-500">{x}</span>)}</div></article>}
function Comparison({title,items,bad=false}:{title:string;items:string[];bad?:boolean}){return <div className={`p-7 sm:p-10 ${bad?'bg-slate-50':'bg-[#0c3156] text-white'}`}><h3 className="text-xl font-black">{title}</h3><div className="mt-6 space-y-3">{items.map(x=><div key={x} className="flex items-center gap-3"><span className={`grid h-6 w-6 place-items-center rounded-full ${bad?'bg-red-100 text-red-600':'bg-emerald-400/15 text-emerald-300'}`}>{bad?'×':<Check size={13}/>}</span><span className={`text-sm font-bold ${bad?'text-slate-600':'text-blue-50'}`}>{x}</span></div>)}</div></div>}
