import type { BOQItem, BusinessParty, CommercialRepository, Contract, CostDimension, PartyType, ProjectBudgetLine, ProjectRecord, Tender, Variation } from '../../domain/commercial';
import type { BaseEntity } from '../../domain/foundation';
import { money } from '../../application/accounting';
import { getDatabase } from './database';

const now=()=>new Date().toISOString();
const entity=(companyId:string,timestamp=now()):BaseEntity=>({id:crypto.randomUUID(),companyId,createdAt:timestamp,updatedAt:timestamp});
const text=(value:string,label:string)=>{const result=value.trim();if(!result)throw new Error(`${label} مطلوب`);return result};

export class IndexedDBCommercialRepository implements CommercialRepository {
  async listParties(companyId:string,type?:PartyType){const rows=await getDatabase().parties.where('companyId').equals(companyId).toArray();return rows.filter(row=>!type||row.type===type).sort((a,b)=>a.arabicName.localeCompare(b.arabicName,'ar'))}
  async saveParty(input:Omit<BusinessParty,keyof BaseEntity>&{id?:string;companyId:string}){
    const db=getDatabase();const timestamp=now();const code=text(input.code,'كود الطرف').toUpperCase();
    const duplicate=await db.parties.where('[companyId+type+code]').equals([input.companyId,input.type,code]).first();
    if(duplicate&&duplicate.id!==input.id)throw new Error('الكود مستخدم لنفس نوع الطرف');
    const old=input.id?await db.parties.get(input.id):undefined;
    const row:BusinessParty={...input,id:input.id||crypto.randomUUID(),code,arabicName:text(input.arabicName,'اسم الطرف'),englishName:input.englishName?.trim()||undefined,paymentTermsDays:Number(input.paymentTermsDays||0),creditLimit:input.creditLimit?money(Number(input.creditLimit)):undefined,createdAt:old?.createdAt||timestamp,updatedAt:timestamp};
    await db.parties.put(row);return row;
  }

  async listProjects(companyId:string){return (await getDatabase().projects.where('companyId').equals(companyId).toArray()).sort((a,b)=>a.code.localeCompare(b.code))}
  async saveProject(input:Omit<ProjectRecord,keyof BaseEntity>&{id?:string;companyId:string}){
    const db=getDatabase();const timestamp=now();const code=text(input.code,'كود المشروع').toUpperCase();const duplicate=await db.projects.where('[companyId+code]').equals([input.companyId,code]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('كود المشروع مستخدم');
    if(input.physicalProgress!==undefined&&(input.physicalProgress<0||input.physicalProgress>100))throw new Error('نسبة التقدم بين 0 و100');
    const old=input.id?await db.projects.get(input.id):undefined;const row:ProjectRecord={...input,id:input.id||crypto.randomUUID(),code,name:text(input.name,'اسم المشروع'),originalContractValue:money(Number(input.originalContractValue||0)),retentionRate:Number(input.retentionRate||0),advanceRate:Number(input.advanceRate||0),physicalProgress:Number(input.physicalProgress||0),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.projects.put(row);return row;
  }

  async listContracts(companyId:string,projectId?:string){const rows=await getDatabase().contracts.where('companyId').equals(companyId).toArray();return rows.filter(row=>!projectId||row.projectId===projectId).sort((a,b)=>a.number.localeCompare(b.number))}
  async saveContract(input:Omit<Contract,keyof BaseEntity|'revisedValue'>&{id?:string;companyId:string}){
    const db=getDatabase();const timestamp=now();const number=text(input.number,'رقم العقد').toUpperCase();const duplicate=await db.contracts.where('[companyId+number]').equals([input.companyId,number]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('رقم العقد مستخدم');
    const project=await db.projects.get(input.projectId);const client=await db.parties.get(input.clientId);if(!project||project.companyId!==input.companyId)throw new Error('المشروع غير صالح');if(!client||client.type!=='client'||client.companyId!==input.companyId)throw new Error('العميل غير صالح');
    const old=input.id?await db.contracts.get(input.id):undefined;const originalValue=money(Number(input.originalValue||0));const approvedVariations=money(Number(input.approvedVariations||0));const row:Contract={...input,id:input.id||crypto.randomUUID(),number,title:text(input.title,'عنوان العقد'),originalValue,approvedVariations,revisedValue:money(originalValue+approvedVariations),retentionRate:Number(input.retentionRate||0),advanceRate:Number(input.advanceRate||0),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.contracts.put(row);return row;
  }

  async listBOQ(companyId:string,projectId?:string){const rows=await getDatabase().boqItems.where('companyId').equals(companyId).toArray();return rows.filter(row=>!projectId||row.projectId===projectId).sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true}))}
  async saveBOQItem(input:Omit<BOQItem,keyof BaseEntity>&{id?:string;companyId:string}){
    const db=getDatabase();const timestamp=now();const code=text(input.code,'كود البند').toUpperCase();const duplicate=await db.boqItems.where('[companyId+projectId+code]').equals([input.companyId,input.projectId,code]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('كود BOQ مستخدم داخل المشروع');
    if(input.quantity<0||input.sellingRate<0||input.budgetCost<0)throw new Error('الكميات والقيم لا تكون سالبة');const old=input.id?await db.boqItems.get(input.id):undefined;const row:BOQItem={...input,id:input.id||crypto.randomUUID(),code,description:text(input.description,'وصف البند'),quantity:Number(input.quantity),sellingRate:money(Number(input.sellingRate)),budgetCost:money(Number(input.budgetCost)),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.boqItems.put(row);return row;
  }
  async removeDraftBOQItem(id:string){const db=getDatabase();const row=await db.boqItems.get(id);if(!row||row.status!=='draft')throw new Error('يمكن حذف بنود المسودة فقط');if(await db.boqItems.where('parentId').equals(id).count())throw new Error('احذف البنود الفرعية أولًا');await db.boqItems.delete(id)}

  async listBudget(companyId:string,projectId?:string){const rows=await getDatabase().projectBudgetLines.where('companyId').equals(companyId).toArray();return rows.filter(row=>!projectId||row.projectId===projectId)}
  async saveBudgetLine(input:Omit<ProjectBudgetLine,keyof BaseEntity>&{id?:string;companyId:string}){if(input.amount<0)throw new Error('قيمة الميزانية لا تكون سالبة');const db=getDatabase();const timestamp=now();const old=input.id?await db.projectBudgetLines.get(input.id):undefined;const row:ProjectBudgetLine={...input,id:input.id||crypto.randomUUID(),description:text(input.description,'الوصف'),amount:money(Number(input.amount)),revisionNumber:Number(input.revisionNumber||0),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.projectBudgetLines.put(row);return row}

  async listDimensions(companyId:string,kind?:CostDimension['kind']){const rows=await getDatabase().costDimensions.where('companyId').equals(companyId).toArray();return rows.filter(row=>!kind||row.kind===kind).sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true}))}
  async saveDimension(input:Omit<CostDimension,keyof BaseEntity>&{id?:string;companyId:string}){const db=getDatabase();const timestamp=now();const code=text(input.code,'الكود').toUpperCase();const duplicate=await db.costDimensions.where('[companyId+kind+code]').equals([input.companyId,input.kind,code]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('الكود مستخدم');if(input.parentId===input.id)throw new Error('العنصر لا يكون أبًا لنفسه');const old=input.id?await db.costDimensions.get(input.id):undefined;const row:CostDimension={...input,id:input.id||crypto.randomUUID(),code,name:text(input.name,'الاسم'),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.costDimensions.put(row);return row}

  async listTenders(companyId:string){return (await getDatabase().tenders.where('companyId').equals(companyId).toArray()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
  async saveTender(input:Omit<Tender,keyof BaseEntity>&{id?:string;companyId:string}){const db=getDatabase();const timestamp=now();const number=text(input.number,'رقم المناقصة').toUpperCase();const duplicate=await db.tenders.where('[companyId+number]').equals([input.companyId,number]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('رقم المناقصة مستخدم');const old=input.id?await db.tenders.get(input.id):undefined;if(old?.convertedProjectId)throw new Error('لا يمكن تعديل مناقصة محولة');const row:Tender={...input,id:input.id||crypto.randomUUID(),number,title:text(input.title,'عنوان المناقصة'),estimatedRevenue:money(Number(input.estimatedRevenue||0)),estimatedCost:money(Number(input.estimatedCost||0)),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.tenders.put(row);return row}
  async convertWonTender(id:string){const db=getDatabase();return db.transaction('rw',[db.tenders,db.projects,db.contracts],async()=>{const tender=await db.tenders.get(id);if(!tender||tender.status!=='won')throw new Error('يجب أن تكون المناقصة Won قبل التحويل');if(tender.convertedProjectId&&tender.convertedContractId)return{projectId:tender.convertedProjectId,contractId:tender.convertedContractId};if(!tender.clientId)throw new Error('حدد العميل قبل التحويل');const timestamp=now();const projectId=crypto.randomUUID(),contractId=crypto.randomUUID();const project:ProjectRecord={...entity(tender.companyId,timestamp),id:projectId,code:`PRJ-${tender.number}`,name:tender.title,clientId:tender.clientId,contractType:tender.contractType,originalContractValue:tender.estimatedRevenue,physicalProgress:0,lifecycleStatus:'draft',status:'active'};const contract:Contract={...entity(tender.companyId,timestamp),id:contractId,projectId,clientId:tender.clientId,number:`CTR-${tender.number}`,title:tender.title,type:tender.contractType,currency:'EGP',originalValue:tender.estimatedRevenue,approvedVariations:0,revisedValue:tender.estimatedRevenue,retentionRate:0,advanceRate:0,startDate:new Date().toISOString().slice(0,10),status:'draft'};await db.projects.add(project);await db.contracts.add(contract);await db.tenders.update(id,{convertedProjectId:projectId,convertedContractId:contractId,updatedAt:timestamp});return{projectId,contractId}})}

  async listVariations(companyId:string,projectId?:string){const rows=await getDatabase().variations.where('companyId').equals(companyId).toArray();return rows.filter(row=>!projectId||row.projectId===projectId)}
  async saveVariation(input:Omit<Variation,keyof BaseEntity>&{id?:string;companyId:string}){const db=getDatabase();const timestamp=now();return db.transaction('rw',[db.variations,db.contracts],async()=>{const number=text(input.number,'رقم التغيير').toUpperCase();const duplicate=await db.variations.where('[companyId+contractId+number]').equals([input.companyId,input.contractId,number]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('رقم التغيير مستخدم للعقد');const old=input.id?await db.variations.get(input.id):undefined;const row:Variation={...input,id:input.id||crypto.randomUUID(),number,title:text(input.title,'عنوان التغيير'),revenueImpact:money(Number(input.revenueImpact||0)),costImpact:money(Number(input.costImpact||0)),budgetImpact:money(Number(input.budgetImpact||0)),timeImpactDays:Number(input.timeImpactDays||0),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.variations.put(row);const contract=await db.contracts.get(input.contractId);if(contract){const approved=await db.variations.where('contractId').equals(contract.id).filter(v=>v.status==='approved').toArray();const sum=money(approved.reduce((s,v)=>s+v.revenueImpact,0));await db.contracts.update(contract.id,{approvedVariations:sum,revisedValue:money(contract.originalValue+sum),updatedAt:timestamp})}return row})}
}
