import { money } from '../../application/accounting';
import type { AccountingMappingKey,JournalLine } from '../../domain/accounting';
import type { CashTransaction,ClientInvoice,FinanceRepository,SubcontractCertificate,SupplierInvoice } from '../../domain/finance';
import type { BaseEntity } from '../../domain/foundation';
import { IndexedDBAccountingRepository } from './accounting-repository';
import { getDatabase } from './database';
const now=()=>new Date().toISOString(),req=(v:string,l:string)=>{const x=v.trim();if(!x)throw new Error(`${l} مطلوب`);return x};
export class IndexedDBFinanceRepository implements FinanceRepository{
 private accounting=new IndexedDBAccountingRepository();
 private async accounts(companyId:string,keys:AccountingMappingKey[]){const db=getDatabase(),maps=await db.accountingMappings.where('companyId').equals(companyId).toArray(),result={} as Record<AccountingMappingKey,string>;for(const key of keys){const id=maps.find(m=>m.key===key)?.accountId;if(!id)throw new Error(`أكمل الربط المحاسبي: ${key}`);result[key]=id}return result}
 private async journal(companyId:string,date:string,description:string,sourceId:string,lines:Array<Pick<JournalLine,'accountId'|'debit'|'credit'|'projectId'|'partyType'|'partyId'>>){const saved=await this.accounting.saveJournal({companyId,date,description,sourceType:'system',sourceId,lines});await this.accounting.approveJournal(saved.entry.id);await this.accounting.postJournal(saved.entry.id);return saved.entry.id}
 async listClientInvoices(companyId:string){return getDatabase().clientInvoices.where('companyId').equals(companyId).reverse().sortBy('date')}
 async saveClientInvoice(input:Omit<ClientInvoice,keyof BaseEntity|'netDue'|'paidAmount'|'journalId'>&{id?:string;companyId:string}){const db=getDatabase(),timestamp=now(),number=req(input.number,'رقم فاتورة العميل').toUpperCase(),dup=await db.clientInvoices.where('[companyId+number]').equals([input.companyId,number]).first();if(dup&&dup.id!==input.id)throw new Error('رقم الفاتورة مستخدم');const contract=await db.contracts.get(input.contractId);if(!contract||contract.projectId!==input.projectId||contract.clientId!==input.clientId)throw new Error('ربط العقد غير صالح');const old=input.id?await db.clientInvoices.get(input.id):undefined;if(old&&old.status!=='draft')throw new Error('يمكن تعديل المسودة فقط');const gross=money(input.grossAmount),ret=money(input.retentionAmount),advance=money(input.advanceRecovery),vat=money(input.vatAmount);if([gross,ret,advance,vat].some(x=>x<0)||ret+advance>gross)throw new Error('قيم المستخلص غير صالحة');const row:ClientInvoice={...input,id:input.id||crypto.randomUUID(),number,grossAmount:gross,retentionAmount:ret,advanceRecovery:advance,vatAmount:vat,netDue:money(gross+vat-ret-advance),paidAmount:old?.paidAmount||0,createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.clientInvoices.put(row);return row}
 async postClientInvoice(id:string){const db=getDatabase();await db.transaction('rw',[db.clientInvoices,db.accountingMappings,db.accounts,db.accountingPeriods,db.journalEntries,db.journalLines],async()=>{const x=await db.clientInvoices.get(id);if(!x)throw new Error('الفاتورة غير موجودة');if(x.status==='posted'||x.status==='part_paid'||x.status==='paid')return;if(x.status!=='draft')throw new Error('لا يمكن ترحيل الفاتورة');const a=await this.accounts(x.companyId,['ar','revenue','vat_output','retention','advances']);const lines=[{accountId:a.ar,debit:x.netDue,credit:0,projectId:x.projectId,partyType:'client' as const,partyId:x.clientId},{accountId:a.retention,debit:x.retentionAmount,credit:0,projectId:x.projectId,partyType:'client' as const,partyId:x.clientId},{accountId:a.advances,debit:x.advanceRecovery,credit:0,projectId:x.projectId,partyType:'client' as const,partyId:x.clientId},{accountId:a.revenue,debit:0,credit:x.grossAmount,projectId:x.projectId},{accountId:a.vat_output,debit:0,credit:x.vatAmount,projectId:x.projectId}].filter(l=>l.debit||l.credit);const journalId=await this.journal(x.companyId,x.date,`فاتورة عميل ${x.number}`,x.id,lines);await db.clientInvoices.update(id,{status:'posted',journalId,updatedAt:now()})})}
 async listSupplierInvoices(companyId:string){return getDatabase().supplierInvoices.where('companyId').equals(companyId).reverse().sortBy('date')}
 async saveSupplierInvoice(input:Omit<SupplierInvoice,keyof BaseEntity|'totalDue'|'paidAmount'|'journalId'>&{id?:string;companyId:string}){const db=getDatabase(),timestamp=now(),number=req(input.number,'رقم فاتورة المورد').toUpperCase(),po=await db.purchaseOrders.get(input.purchaseOrderId);if(!po||po.companyId!==input.companyId||po.supplierId!==input.supplierId)throw new Error('أمر الشراء غير صالح');const dup=await db.supplierInvoices.where('[companyId+supplierId+number]').equals([input.companyId,input.supplierId,number]).first();if(dup&&dup.id!==input.id)throw new Error('فاتورة المورد مكررة');const old=input.id?await db.supplierInvoices.get(input.id):undefined;if(old&&old.status!=='draft')throw new Error('يمكن تعديل المسودة فقط');const net=money(input.netAmount),vat=money(input.vatAmount);if(net<0||vat<0)throw new Error('قيم الفاتورة غير صالحة');const row:SupplierInvoice={...input,id:input.id||crypto.randomUUID(),number,netAmount:net,vatAmount:vat,totalDue:money(net+vat),paidAmount:old?.paidAmount||0,createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.supplierInvoices.put(row);return row}
 async postSupplierInvoice(id:string){const db=getDatabase();await db.transaction('rw',[db.supplierInvoices,db.accountingMappings,db.accounts,db.accountingPeriods,db.journalEntries,db.journalLines],async()=>{const x=await db.supplierInvoices.get(id);if(!x)throw new Error('الفاتورة غير موجودة');if(x.status==='posted'||x.status==='part_paid'||x.status==='paid')return;if(x.status!=='draft')throw new Error('لا يمكن الترحيل');const a=await this.accounts(x.companyId,['supply_cost','vat_input','ap']);const lines=[{accountId:a.supply_cost,debit:x.netAmount,credit:0,projectId:x.projectId},{accountId:a.vat_input,debit:x.vatAmount,credit:0,projectId:x.projectId},{accountId:a.ap,debit:0,credit:x.totalDue,projectId:x.projectId,partyType:'supplier' as const,partyId:x.supplierId}].filter(l=>l.debit||l.credit);const journalId=await this.journal(x.companyId,x.date,`فاتورة مورد ${x.number}`,x.id,lines);await db.supplierInvoices.update(id,{status:'posted',journalId,updatedAt:now()})})}
 async listSubcontractCertificates(companyId:string){return getDatabase().subcontractCertificates.where('companyId').equals(companyId).reverse().sortBy('date')}
 async saveSubcontractCertificate(input:Omit<SubcontractCertificate,keyof BaseEntity|'netDue'|'paidAmount'|'journalId'>&{id?:string;companyId:string}){const db=getDatabase(),timestamp=now(),number=req(input.number,'رقم مستخلص المقاول').toUpperCase(),party=await db.parties.get(input.subcontractorId);if(!party||party.type!=='subcontractor'||party.companyId!==input.companyId)throw new Error('مقاول الباطن غير صالح');const dup=await db.subcontractCertificates.where('[companyId+subcontractorId+number]').equals([input.companyId,input.subcontractorId,number]).first();if(dup&&dup.id!==input.id)throw new Error('رقم المستخلص مكرر');const old=input.id?await db.subcontractCertificates.get(input.id):undefined;if(old&&old.status!=='draft')throw new Error('يمكن تعديل المسودة فقط');const gross=money(input.currentAmount??input.grossAmount),ret=money(input.retentionAmount),advance=money(input.advanceRecovery),tax=money(input.taxAmount||0),deductions=money(input.deductions||0),previous=money(input.previousAmount||0);if(gross<0||ret<0||advance<0||tax<0||deductions<0||ret+advance+deductions>gross+tax)throw new Error('قيم المستخلص غير صالحة');const row:SubcontractCertificate={...input,id:input.id||crypto.randomUUID(),number,previousAmount:previous,currentAmount:gross,cumulativeAmount:money(previous+gross),grossAmount:gross,retentionAmount:ret,advanceRecovery:advance,taxAmount:tax,deductions,netDue:money(gross+tax-ret-advance-deductions),paidAmount:old?.paidAmount||0,createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.subcontractCertificates.put(row);return row}
 async postSubcontractCertificate(id:string){const db=getDatabase();await db.transaction('rw',[db.subcontractCertificates,db.accountingMappings,db.accounts,db.accountingPeriods,db.journalEntries,db.journalLines],async()=>{const x=await db.subcontractCertificates.get(id);if(!x)throw new Error('المستخلص غير موجود');if(x.status!=='draft')return;const required:AccountingMappingKey[]=['subcontractor_cost','ap','retention','advances','vat_input',...(x.deductions?['accruals' as const]:[])],a=await this.accounts(x.companyId,required);const lines=[{accountId:a.subcontractor_cost,debit:x.grossAmount,credit:0,projectId:x.projectId},{accountId:a.vat_input,debit:x.taxAmount||0,credit:0,projectId:x.projectId},{accountId:a.ap,debit:0,credit:x.netDue,projectId:x.projectId,partyType:'subcontractor' as const,partyId:x.subcontractorId},{accountId:a.retention,debit:0,credit:x.retentionAmount,projectId:x.projectId},{accountId:a.advances,debit:0,credit:x.advanceRecovery,projectId:x.projectId},{accountId:a.accruals,debit:0,credit:x.deductions||0,projectId:x.projectId}].filter(l=>l.debit||l.credit);const journalId=await this.journal(x.companyId,x.date,`مستخلص مقاول باطن ${x.number}`,x.id,lines);await db.subcontractCertificates.update(id,{status:'posted',journalId,updatedAt:now()})})}
 async listCashTransactions(companyId:string){return getDatabase().cashTransactions.where('companyId').equals(companyId).reverse().sortBy('date')}
 async saveCashTransaction(input:Omit<CashTransaction,keyof BaseEntity|'journalId'>&{id?:string;companyId:string}){if(input.amount<=0)throw new Error('المبلغ يجب أن يكون أكبر من صفر');const db=getDatabase(),timestamp=now(),number=req(input.number,'رقم السند').toUpperCase(),dup=await db.cashTransactions.where('[companyId+number]').equals([input.companyId,number]).first();if(dup&&dup.id!==input.id)throw new Error('رقم السند مستخدم');const old=input.id?await db.cashTransactions.get(input.id):undefined;if(old&&old.status!=='draft')throw new Error('يمكن تعديل المسودة فقط');const row:CashTransaction={...input,id:input.id||crypto.randomUUID(),number,amount:money(input.amount),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.cashTransactions.put(row);return row}
 async postCashTransaction(id:string){const db=getDatabase();await db.transaction('rw',[db.cashTransactions,db.clientInvoices,db.supplierInvoices,db.subcontractCertificates,db.accountingMappings,db.accounts,db.accountingPeriods,db.journalEntries,db.journalLines],async()=>{const x=await db.cashTransactions.get(id);if(!x)throw new Error('السند غير موجود');if(x.status==='posted')return;if(x.status!=='draft')throw new Error('لا يمكن ترحيل السند');const table=x.sourceType==='client_invoice'?db.clientInvoices:x.sourceType==='supplier_invoice'?db.supplierInvoices:db.subcontractCertificates,doc=await table.get(x.sourceId);if(!doc||doc.companyId!==x.companyId||!['posted','part_paid'].includes(doc.status))throw new Error('المستند المصدر غير قابل للسداد');const due='netDue' in doc?doc.netDue:doc.totalDue,remaining=money(due-doc.paidAmount);if(x.amount>remaining)throw new Error('المبلغ يتجاوز الرصيد المستحق');const cashKey=x.treasuryType==='cash'?'cash':'bank',counter=x.direction==='receipt'?'ar':'ap',a=await this.accounts(x.companyId,[cashKey,counter]);const lines=x.direction==='receipt'?[{accountId:a[cashKey],debit:x.amount,credit:0},{accountId:a[counter],debit:0,credit:x.amount,partyType:x.partyType,partyId:x.partyId}]:[{accountId:a[counter],debit:x.amount,credit:0,partyType:x.partyType,partyId:x.partyId},{accountId:a[cashKey],debit:0,credit:x.amount}];const journalId=await this.journal(x.companyId,x.date,`${x.direction==='receipt'?'سند قبض':'سند صرف'} ${x.number}`,x.id,lines);const paidAmount=money(doc.paidAmount+x.amount);await table.update(doc.id,{paidAmount,status:paidAmount===due?'paid':'part_paid',updatedAt:now()});await db.cashTransactions.update(id,{status:'posted',journalId,updatedAt:now()})})}
}
