import { money } from '../../application/accounting';
import type { BaseEntity } from '../../domain/foundation';
import type { ClientDelivery, DeliveryInspection, GoodsReceipt, InventoryItem, InventoryRepository, PurchaseReturnRecord, StockMovement } from '../../domain/inventory';
import { getDatabase } from './database';

const now=()=>new Date().toISOString(); const required=(v:string,l:string)=>{const x=v.trim();if(!x)throw new Error(`${l} مطلوب`);return x};
export class IndexedDBInventoryRepository implements InventoryRepository {
 async listItems(companyId:string){return getDatabase().inventoryItems.where('companyId').equals(companyId).sortBy('code')}
 async saveItem(input:Omit<InventoryItem,keyof BaseEntity>&{id?:string;companyId:string}){const db=getDatabase(),timestamp=now(),code=required(input.code,'كود الصنف').toUpperCase(),duplicate=await db.inventoryItems.where('[companyId+code]').equals([input.companyId,code]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('كود الصنف مستخدم');const old=input.id?await db.inventoryItems.get(input.id):undefined,row:InventoryItem={...input,id:input.id||crypto.randomUUID(),code,name:required(input.name,'اسم الصنف'),unit:required(input.unit,'الوحدة'),reorderLevel:Number(input.reorderLevel||0),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.inventoryItems.put(row);return row}
 async listReceipts(companyId:string){return getDatabase().goodsReceipts.where('companyId').equals(companyId).reverse().sortBy('createdAt')}
 async saveReceipt(input:Omit<GoodsReceipt,keyof BaseEntity>&{id?:string;companyId:string}){if(input.quantity<=0||input.unitCost<0)throw new Error('كمية أو تكلفة الاستلام غير صالحة');const db=getDatabase(),timestamp=now(),number=required(input.number,'رقم الاستلام').toUpperCase(),po=await db.purchaseOrders.get(input.purchaseOrderId);if(!po||po.companyId!==input.companyId||po.status!=='approved')throw new Error('الاستلام يحتاج أمر شراء معتمد');const item=await db.inventoryItems.get(input.itemId);if(!item||item.companyId!==input.companyId)throw new Error('الصنف غير صالح');if(input.scenario!=='direct_to_client'&&!input.warehouseId)throw new Error('حدد المخزن للاستلام المخزني');const already=(await db.goodsReceipts.where('purchaseOrderId').equals(po.id).filter(x=>x.status==='posted'&&x.id!==input.id).toArray()).reduce((s,x)=>s+x.quantity,0);if(already+input.quantity>po.quantity)throw new Error('كمية الاستلام تتجاوز أمر الشراء');const duplicate=await db.goodsReceipts.where('[companyId+number]').equals([input.companyId,number]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('رقم الاستلام مستخدم');const old=input.id?await db.goodsReceipts.get(input.id):undefined;if(old&&old.status!=='draft')throw new Error('يمكن تعديل المسودة فقط');const row:GoodsReceipt={...input,id:input.id||crypto.randomUUID(),number,quantity:Number(input.quantity),unitCost:money(Number(input.unitCost)),warehouseId:input.warehouseId||undefined,createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.goodsReceipts.put(row);return row}
 async postReceipt(id:string){const db=getDatabase();await db.transaction('rw',[db.goodsReceipts,db.stockMovements],async()=>{const row=await db.goodsReceipts.get(id);if(!row)throw new Error('الاستلام غير موجود');if(row.status==='posted')return;if(row.status!=='draft')throw new Error('لا يمكن ترحيل هذا الاستلام');const timestamp=now();if(row.scenario!=='direct_to_client'&&row.warehouseId){const movement:StockMovement={id:crypto.randomUUID(),companyId:row.companyId,itemId:row.itemId,warehouseId:row.warehouseId,projectId:row.projectId,sourceType:'receipt',sourceId:row.id,date:row.receivedAt,quantityIn:row.quantity,quantityOut:0,unitCost:row.unitCost,createdAt:timestamp,updatedAt:timestamp};await db.stockMovements.add(movement)}await db.goodsReceipts.update(id,{status:'posted',updatedAt:timestamp})})}
 async listMovements(companyId:string){return getDatabase().stockMovements.where('companyId').equals(companyId).sortBy('date')}
 async getOnHand(companyId:string,itemId:string,warehouseId:string){const rows=await getDatabase().stockMovements.where('[companyId+itemId+warehouseId]').equals([companyId,itemId,warehouseId]).toArray();return rows.reduce((s,x)=>s+x.quantityIn-x.quantityOut,0)}
 async listDeliveries(companyId:string){return getDatabase().clientDeliveries.where('companyId').equals(companyId).reverse().sortBy('createdAt')}
 async saveDelivery(input:Omit<ClientDelivery,keyof BaseEntity>&{id?:string;companyId:string}){if(input.quantity<=0)throw new Error('كمية التسليم يجب أن تكون أكبر من صفر');const db=getDatabase(),timestamp=now(),receipt=await db.goodsReceipts.get(input.receiptId);if(!receipt||receipt.companyId!==input.companyId||receipt.status!=='posted')throw new Error('التسليم يحتاج استلامًا مرحلًا');const delivered=(await db.clientDeliveries.where('receiptId').equals(receipt.id).filter(x=>x.status==='posted'&&x.id!==input.id).toArray()).reduce((s,x)=>s+x.quantity,0);if(delivered+input.quantity>receipt.quantity)throw new Error('كمية التسليم تتجاوز المستلم');const number=required(input.number,'رقم التسليم').toUpperCase(),duplicate=await db.clientDeliveries.where('[companyId+number]').equals([input.companyId,number]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('رقم التسليم مستخدم');const old=input.id?await db.clientDeliveries.get(input.id):undefined;if(old&&old.status!=='draft')throw new Error('يمكن تعديل المسودة فقط');const row:ClientDelivery={...input,id:input.id||crypto.randomUUID(),number,warehouseId:receipt.warehouseId,scenario:receipt.scenario,projectId:receipt.projectId,itemId:receipt.itemId,createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.clientDeliveries.put(row);return row}
 async postDelivery(id:string){const db=getDatabase();await db.transaction('rw',[db.clientDeliveries,db.goodsReceipts,db.stockMovements],async()=>{const row=await db.clientDeliveries.get(id);if(!row)throw new Error('التسليم غير موجود');if(row.status==='posted')return;if(row.status!=='draft')throw new Error('لا يمكن ترحيل التسليم');const receipt=await db.goodsReceipts.get(row.receiptId);if(!receipt)throw new Error('مرجع الاستلام مفقود');const timestamp=now();if(row.scenario!=='direct_to_client'&&row.warehouseId){const onHand=await this.getOnHand(row.companyId,row.itemId,row.warehouseId);if(onHand<row.quantity)throw new Error('الرصيد غير كافٍ للتسليم');await db.stockMovements.add({id:crypto.randomUUID(),companyId:row.companyId,itemId:row.itemId,warehouseId:row.warehouseId,projectId:row.projectId,sourceType:'delivery',sourceId:row.id,date:row.deliveredAt,quantityIn:0,quantityOut:row.quantity,unitCost:receipt.unitCost,createdAt:timestamp,updatedAt:timestamp})}await db.clientDeliveries.update(id,{status:'posted',updatedAt:timestamp})})}
 async listInspections(companyId:string){return getDatabase().deliveryInspections.where('companyId').equals(companyId).reverse().sortBy('createdAt')}
 async saveInspection(input:Omit<DeliveryInspection,keyof BaseEntity>&{id?:string;companyId:string}){if(input.acceptedQuantity<0||input.rejectedQuantity<0)throw new Error('كميات الفحص لا تكون سالبة');const db=getDatabase(),timestamp=now(),delivery=await db.clientDeliveries.get(input.deliveryId);if(!delivery||delivery.companyId!==input.companyId||delivery.status!=='posted')throw new Error('الفحص يحتاج تسليمًا مرحلًا');if(input.acceptedQuantity+input.rejectedQuantity>delivery.quantity)throw new Error('كميات الفحص تتجاوز التسليم');const number=required(input.number,'رقم الفحص').toUpperCase(),duplicate=await db.deliveryInspections.where('[companyId+number]').equals([input.companyId,number]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('رقم الفحص مستخدم');const old=input.id?await db.deliveryInspections.get(input.id):undefined,row:DeliveryInspection={...input,id:input.id||crypto.randomUUID(),number,createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.deliveryInspections.put(row);return row}
 async listReturns(companyId:string){return getDatabase().purchaseReturns.where('companyId').equals(companyId).reverse().sortBy('createdAt')}
 async saveReturn(input:Omit<PurchaseReturnRecord,keyof BaseEntity>&{id?:string;companyId:string}){if(input.quantity<=0)throw new Error('كمية المرتجع يجب أن تكون أكبر من صفر');const db=getDatabase(),timestamp=now(),receipt=await db.goodsReceipts.get(input.receiptId);if(!receipt||receipt.companyId!==input.companyId||receipt.status!=='posted')throw new Error('المرتجع يحتاج استلامًا مرحلًا');const returned=(await db.purchaseReturns.where('receiptId').equals(receipt.id).filter(x=>x.status==='posted'&&x.id!==input.id).toArray()).reduce((s,x)=>s+x.quantity,0);if(returned+input.quantity>receipt.quantity)throw new Error('كمية المرتجع تتجاوز المستلم');const number=required(input.number,'رقم المرتجع').toUpperCase(),duplicate=await db.purchaseReturns.where('[companyId+number]').equals([input.companyId,number]).first();if(duplicate&&duplicate.id!==input.id)throw new Error('رقم المرتجع مستخدم');const old=input.id?await db.purchaseReturns.get(input.id):undefined,row:PurchaseReturnRecord={...input,id:input.id||crypto.randomUUID(),number,itemId:receipt.itemId,warehouseId:receipt.warehouseId,reason:required(input.reason,'سبب المرتجع'),createdAt:old?.createdAt||timestamp,updatedAt:timestamp};await db.purchaseReturns.put(row);return row}
 async postReturn(id:string){const db=getDatabase();await db.transaction('rw',[db.purchaseReturns,db.goodsReceipts,db.stockMovements],async()=>{const row=await db.purchaseReturns.get(id);if(!row)throw new Error('المرتجع غير موجود');if(row.status==='posted')return;if(row.status!=='draft')throw new Error('لا يمكن ترحيل المرتجع');const receipt=await db.goodsReceipts.get(row.receiptId);if(!receipt)throw new Error('مرجع الاستلام مفقود');const timestamp=now();if(row.warehouseId){const onHand=await this.getOnHand(row.companyId,row.itemId,row.warehouseId);if(onHand<row.quantity)throw new Error('الرصيد غير كافٍ للمرتجع');await db.stockMovements.add({id:crypto.randomUUID(),companyId:row.companyId,itemId:row.itemId,warehouseId:row.warehouseId,projectId:receipt.projectId,sourceType:'return',sourceId:row.id,date:row.returnedAt,quantityIn:0,quantityOut:row.quantity,unitCost:receipt.unitCost,createdAt:timestamp,updatedAt:timestamp})}await db.purchaseReturns.update(id,{status:'posted',updatedAt:timestamp})})}
}
