import { money } from '../../application/accounting';
import type { AccountingMappingKey } from '../../domain/accounting';
import type { BaseEntity } from '../../domain/foundation';
import type { BankGuaranteeRecord, DepreciationRun, EquipmentRecord, EquipmentUsage, ExpenseRecord, FixedAssetRecord, TimesheetRecord } from '../../domain/resources';
import { IndexedDBAccountingRepository } from './accounting-repository';
import { getDatabase } from './database';

const now=()=>new Date().toISOString();
const required=(value:string,label:string)=>{const result=value.trim();if(!result)throw new Error(`${label} مطلوب`);return result};
const row=<T extends BaseEntity>(input:Omit<T,keyof BaseEntity>&{id?:string;companyId:string},old?:T)=>({...input,id:input.id||crypto.randomUUID(),createdAt:old?.createdAt||now(),updatedAt:now()}) as T;

export class IndexedDBResourcesRepository {
  private accounting=new IndexedDBAccountingRepository();
  private async mapping(companyId:string,keys:AccountingMappingKey[]){const mappings=await getDatabase().accountingMappings.where('companyId').equals(companyId).toArray(),result:Record<string,string>={};for(const key of keys){const found=mappings.find(x=>x.key===key);if(!found)throw new Error(`الربط المحاسبي ${key} مطلوب`);result[key]=found.accountId}return result}
  private async journal(companyId:string,date:string,description:string,sourceId:string,debitKey:AccountingMappingKey,creditKey:AccountingMappingKey,amount:number,projectId?:string){const a=await this.mapping(companyId,[debitKey,creditKey]);const journal=await this.accounting.saveJournal({companyId,date,description,sourceType:'system',sourceId,lines:[{accountId:a[debitKey],debit:amount,credit:0,projectId},{accountId:a[creditKey],debit:0,credit:amount,projectId}]});await this.accounting.approveJournal(journal.entry.id);await this.accounting.postJournal(journal.entry.id);return journal.entry.id}

  async listExpenses(companyId:string){return getDatabase().expenses.where('companyId').equals(companyId).reverse().sortBy('date')}
  async saveExpense(input:Omit<ExpenseRecord,keyof BaseEntity>&{id?:string;companyId:string}){if(input.amount<=0)throw new Error('المبلغ أكبر من صفر');const db=getDatabase(),old=input.id?await db.expenses.get(input.id):undefined;if(old&&old.status!=='draft')throw new Error('تعديل المسودة فقط');const value=row<ExpenseRecord>({...input,number:required(input.number,'الرقم').toUpperCase(),category:required(input.category,'التصنيف'),description:required(input.description,'الوصف'),amount:money(input.amount)},old);await db.expenses.put(value);return value}
  async postExpense(id:string){const db=getDatabase(),value=await db.expenses.get(id);if(!value||value.status!=='approved')throw new Error('اعتمد المصروف أولًا');const journalId=await this.journal(value.companyId,value.date,`مصروف ${value.number}`,value.id,'supply_cost','cash',value.amount,value.projectId);await db.expenses.update(id,{status:'posted',journalId,updatedAt:now()})}

  async listTimesheets(companyId:string){return getDatabase().timesheets.where('companyId').equals(companyId).reverse().sortBy('date')}
  async saveTimesheet(input:Omit<TimesheetRecord,keyof BaseEntity|'totalCost'>&{id?:string;companyId:string}){if(input.regularHours<0||input.overtimeHours<0||input.hourlyRate<0||input.regularHours+input.overtimeHours>24)throw new Error('ساعات غير صالحة');const db=getDatabase(),old=input.id?await db.timesheets.get(input.id):undefined,value=row<TimesheetRecord>({...input,number:required(input.number,'الرقم').toUpperCase(),employeeCode:required(input.employeeCode,'كود الموظف').toUpperCase(),employeeName:required(input.employeeName,'الموظف'),totalCost:money((input.regularHours+input.overtimeHours*1.5)*input.hourlyRate)},old);await db.timesheets.put(value);return value}
  async postTimesheet(id:string){const db=getDatabase(),value=await db.timesheets.get(id);if(!value||value.status!=='approved')throw new Error('اعتمد كشف الوقت أولًا');const journalId=await this.journal(value.companyId,value.date,`عمالة ${value.number}`,value.id,'labor_cost','accruals',value.totalCost,value.projectId);await db.timesheets.update(id,{status:'posted',journalId,updatedAt:now()})}

  async listEquipment(companyId:string){return getDatabase().equipment.where('companyId').equals(companyId).reverse().sortBy('createdAt')}
  async saveEquipment(input:Omit<EquipmentRecord,keyof BaseEntity>&{id?:string;companyId:string}){if(input.hourlyRate<0||input.meterReading<0)throw new Error('قيم المعدة غير صالحة');const db=getDatabase(),old=input.id?await db.equipment.get(input.id):undefined,value=row<EquipmentRecord>({...input,code:required(input.code,'الكود').toUpperCase(),name:required(input.name,'الاسم')},old);await db.equipment.put(value);return value}
  async listUsage(companyId:string){return getDatabase().equipmentUsage.where('companyId').equals(companyId).reverse().sortBy('date')}
  async saveUsage(input:Omit<EquipmentUsage,keyof BaseEntity|'cost'>&{id?:string;companyId:string}){if(input.hours<=0)throw new Error('الساعات أكبر من صفر');const db=getDatabase(),equipment=await db.equipment.get(input.equipmentId);if(!equipment||equipment.companyId!==input.companyId)throw new Error('المعدة غير صالحة');const old=input.id?await db.equipmentUsage.get(input.id):undefined,value=row<EquipmentUsage>({...input,number:required(input.number,'الرقم').toUpperCase(),cost:money(input.hours*equipment.hourlyRate)},old);await db.equipmentUsage.put(value);return value}
  async postUsage(id:string){const db=getDatabase(),value=await db.equipmentUsage.get(id);if(!value||value.status!=='approved')throw new Error('اعتمد تشغيل المعدة أولًا');const journalId=await this.journal(value.companyId,value.date,`تشغيل معدة ${value.number}`,value.id,'equipment_cost','accruals',value.cost,value.projectId);await db.equipmentUsage.update(id,{status:'posted',journalId,updatedAt:now()})}

  async listAssets(companyId:string){return getDatabase().fixedAssets.where('companyId').equals(companyId).reverse().sortBy('purchaseDate')}
  async saveAsset(input:Omit<FixedAssetRecord,keyof BaseEntity|'accumulatedDepreciation'|'netBookValue'>&{id?:string;companyId:string}){if(input.cost<=0||input.residualValue<0||input.residualValue>=input.cost||input.usefulLifeMonths<=0)throw new Error('قيم الأصل غير صالحة');const db=getDatabase(),old=input.id?await db.fixedAssets.get(input.id):undefined,acc=old?.accumulatedDepreciation||0,value=row<FixedAssetRecord>({...input,code:required(input.code,'الكود').toUpperCase(),name:required(input.name,'الاسم'),category:required(input.category,'التصنيف'),accumulatedDepreciation:acc,netBookValue:money(input.cost-acc)},old);await db.fixedAssets.put(value);return value}
  async listDepreciation(companyId:string){return getDatabase().depreciationRuns.where('companyId').equals(companyId).reverse().sortBy('period')}
  async runDepreciation(companyId:string,assetId:string,period:string,number:string){const db=getDatabase(),asset=await db.fixedAssets.get(assetId);if(!asset||asset.companyId!==companyId||asset.status!=='active')throw new Error('الأصل غير صالح');const duplicate=await db.depreciationRuns.where('[assetId+period]').equals([assetId,period]).first();if(duplicate)return duplicate;const monthly=money((asset.cost-asset.residualValue)/asset.usefulLifeMonths),amount=Math.max(0,Math.min(monthly,money(asset.netBookValue-asset.residualValue))),value=row<DepreciationRun>({companyId,number:required(number,'الرقم').toUpperCase(),assetId,period,amount,status:'draft'});await db.transaction('rw',[db.depreciationRuns,db.fixedAssets],async()=>{await db.depreciationRuns.add(value);await db.fixedAssets.update(assetId,{accumulatedDepreciation:money(asset.accumulatedDepreciation+amount),netBookValue:money(asset.netBookValue-amount),updatedAt:now()})});return value}
  async postDepreciation(id:string,date:string){const db=getDatabase(),value=await db.depreciationRuns.get(id);if(!value||value.status!=='draft')throw new Error('تشغيل الإهلاك غير صالح');const journalId=await this.journal(value.companyId,date,`إهلاك ${value.number}`,value.id,'depreciation','fixed_assets',value.amount);await db.depreciationRuns.update(id,{status:'posted',journalId,updatedAt:now()})}

  async listGuarantees(companyId:string){return getDatabase().bankGuarantees.where('companyId').equals(companyId).reverse().sortBy('expiryDate')}
  async saveGuarantee(input:Omit<BankGuaranteeRecord,keyof BaseEntity>&{id?:string;companyId:string}){if(input.amount<=0||input.expiryDate<input.issueDate)throw new Error('بيانات الضمان غير صالحة');const db=getDatabase(),old=input.id?await db.bankGuarantees.get(input.id):undefined,value=row<BankGuaranteeRecord>({...input,number:required(input.number,'الرقم').toUpperCase(),bankName:required(input.bankName,'البنك'),beneficiary:required(input.beneficiary,'المستفيد'),amount:money(input.amount)},old);await db.bankGuarantees.put(value);return value}
}
