'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Menu, Save, X } from 'lucide-react';
import type { BOQItem, BusinessParty, Contract, ProjectRecord } from '../../domain/commercial';
import type { Company } from '../../domain/foundation';
import type { MaterialRequirement, ProcurementStatus, PurchaseOrder, PurchaseRequisition, RequestForQuotation, SupplierQuote, SupplyPlan } from '../../domain/procurement';
import { IndexedDBCommercialRepository } from '../../infrastructure/indexeddb/commercial-repository';
import { IndexedDBProcurementRepository } from '../../infrastructure/indexeddb/procurement-repository';
import { IndexedDBCompanyRepository, IndexedDBFoundationRepository } from '../../infrastructure/indexeddb/repositories';
import { ErpSidebar } from '../erp-sidebar';

export type ProcurementModule = 'supply-plans'|'material-requirements'|'purchase-requisitions'|'rfqs'|'supplier-quotes'|'purchase-orders';
const titles: Record<ProcurementModule, [string,string]> = {
  'supply-plans':['خطط التوريد','Supply Plans'], 'material-requirements':['احتياجات المواد','Material Requirements'],
  'purchase-requisitions':['طلبات الشراء PR','Purchase Requisitions'], rfqs:['طلبات عروض الأسعار RFQ','Requests for Quotation'],
  'supplier-quotes':['مقارنة عروض الموردين','Supplier Quotations'], 'purchase-orders':['أوامر الشراء PO','Purchase Orders'],
};

export function ProcurementApp({module}:{module:ProcurementModule}) {
  const repository=useMemo(()=>new IndexedDBProcurementRepository(),[]), commercial=useMemo(()=>new IndexedDBCommercialRepository(),[]), foundation=useMemo(()=>new IndexedDBFoundationRepository(),[]), companies=useMemo(()=>new IndexedDBCompanyRepository(),[]);
  const [company,setCompany]=useState<Company>(),[projects,setProjects]=useState<ProjectRecord[]>([]),[contracts,setContracts]=useState<Contract[]>([]),[boq,setBoq]=useState<BOQItem[]>([]),[suppliers,setSuppliers]=useState<BusinessParty[]>([]),[plans,setPlans]=useState<SupplyPlan[]>([]),[requirements,setRequirements]=useState<MaterialRequirement[]>([]),[requisitions,setRequisitions]=useState<PurchaseRequisition[]>([]),[rfqs,setRfqs]=useState<RequestForQuotation[]>([]),[quotes,setQuotes]=useState<SupplierQuote[]>([]),[orders,setOrders]=useState<PurchaseOrder[]>([]),[loading,setLoading]=useState(true),[nav,setNav]=useState(false),[message,setMessage]=useState('');
  const reload=useCallback(async()=>{const id=await foundation.getActiveCompanyId();if(!id){setLoading(false);return}const [c,p,ct,b,s,sp,mr,pr,rf,q,po]=await Promise.all([companies.get(id),commercial.listProjects(id),commercial.listContracts(id),commercial.listBOQ(id),commercial.listParties(id,'supplier'),repository.listSupplyPlans(id),repository.listRequirements(id),repository.listRequisitions(id),repository.listRFQs(id),repository.listQuotes(id),repository.listPurchaseOrders(id)]);setCompany(c);setProjects(p);setContracts(ct);setBoq(b);setSuppliers(s);setPlans(sp);setRequirements(mr);setRequisitions(pr);setRfqs(rf);setQuotes(q);setOrders(po);setLoading(false)},[commercial,companies,foundation,repository]);
  useEffect(()=>{
    // IndexedDB is loaded after the client mounts.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void reload();
  },[reload]);
  const notify=(value:string)=>setMessage(value);
  if(loading)return <div className="grid min-h-screen place-items-center bg-[#F6F8FB]" dir="rtl">تحميل البيانات المحلية...</div>;
  if(!company)return <main className="grid min-h-screen place-items-center bg-[#F6F8FB]" dir="rtl"><Link href="/setup" className="rounded-xl bg-[#287C8E] px-6 py-3 font-bold text-white">أنشئ الشركة أولًا</Link></main>;
  return <main className="min-h-screen bg-[#F6F8FB] text-[#1C2B3A]" dir="rtl"><div className="flex min-h-screen"><ErpSidebar open={nav} onClose={()=>setNav(false)}/><section className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-[72px] items-center gap-3 border-b border-[#DDE5EC] bg-white/95 px-4 sm:px-8"><button className="lg:hidden" onClick={()=>setNav(true)}><Menu/></button><div><p className="text-sm font-extrabold">{company.arabicName}</p><p className="text-[11px] text-slate-500">{titles[module][1]} · Local</p></div></header><div className="mx-auto max-w-[1380px] p-4 sm:p-8">{message&&<Notice text={message} close={()=>setMessage('')}/>}<Header module={module}/>
    {module==='supply-plans'&&<Plans company={company} rows={plans} projects={projects} contracts={contracts} repository={repository} reload={reload} notify={notify}/>} 
    {module==='material-requirements'&&<Requirements company={company} rows={requirements} plans={plans} boq={boq} repository={repository} reload={reload} notify={notify}/>} 
    {module==='purchase-requisitions'&&<Requisitions company={company} rows={requisitions} projects={projects} requirements={requirements} repository={repository} reload={reload} notify={notify}/>} 
    {module==='rfqs'&&<RFQs company={company} rows={rfqs} requisitions={requisitions} suppliers={suppliers} repository={repository} reload={reload} notify={notify}/>} 
    {module==='supplier-quotes'&&<Quotes company={company} rows={quotes} rfqs={rfqs} suppliers={suppliers} repository={repository} reload={reload} notify={notify}/>} 
    {module==='purchase-orders'&&<Orders rows={orders} suppliers={suppliers} repository={repository} reload={reload} notify={notify}/>} 
  </div></section></div></main>;
}

function Notice({text,close}:{text:string;close:()=>void}){return <div className="mb-5 flex justify-between rounded-xl border border-teal-200 bg-teal-50 p-4 text-sm font-bold text-teal-900"><span>{text}</span><button onClick={close}><X size={16}/></button></div>}
function Header({module}:{module:ProcurementModule}){return <div className="mb-7"><p className="text-xs font-bold text-[#287C8E]">{titles[module][1]}</p><h1 className="mt-2 text-3xl font-black text-[#17324D]">{titles[module][0]}</h1><p className="mt-2 text-sm text-slate-500">مستندات فعلية محفوظة محليًا؛ لا تُنشأ التزامات من بيانات وهمية.</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field-label">{label}{children}</label>}
function Form({children,save}:{children:React.ReactNode;save:()=>void}){return <section className="mb-6 rounded-2xl border border-[#DDE5EC] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{children}</div><button onClick={save} className="mt-5 flex items-center gap-2 rounded-xl bg-[#35A89A] px-5 py-2.5 text-xs font-bold text-white"><Save size={15}/>حفظ</button></section>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-[#DDE5EC] bg-white p-10 text-center text-sm font-bold">{text}</div>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{children}</div>}
function Card({title,code,detail,actions}:{title:string;code:string;detail:string;actions?:React.ReactNode}){return <article className="rounded-2xl border border-[#DDE5EC] bg-white p-5"><p className="text-[10px] font-bold text-[#287C8E]">{code}</p><h3 className="mt-1 font-black text-[#17324D]">{title}</h3><p className="mt-3 text-xs leading-6 text-slate-500">{detail}</p>{actions&&<div className="mt-4 flex flex-wrap gap-2">{actions}</div>}</article>}
const action=(label:string,run:()=>void)=><button onClick={run} className="rounded-lg bg-[#287C8E] px-3 py-2 text-[10px] font-bold text-white">{label}</button>;

function Plans({company,rows,projects,contracts,repository,reload,notify}:{company:Company;rows:SupplyPlan[];projects:ProjectRecord[];contracts:Contract[];repository:IndexedDBProcurementRepository;reload:()=>Promise<void>;notify:(x:string)=>void}){
  const [form,setForm]=useState({projectId:projects[0]?.id||'',contractId:contracts.find(c=>c.projectId===projects[0]?.id)?.id||'',number:'',revision:0,baselineDate:'',notes:'',status:'draft' as ProcurementStatus});
  const save=async()=>{try{await repository.saveSupplyPlan({...form,companyId:company.id});setForm({...form,number:'',notes:''});notify('تم حفظ خطة التوريد.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر الحفظ')}};
  if(!projects.length||!contracts.length)return <Empty text="أنشئ مشروعًا وعقدًا قبل خطة التوريد."/>;
  return <><Form save={save}><Field label="المشروع"><select className="field-input" value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value,contractId:contracts.find(c=>c.projectId===e.target.value)?.id||''})}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="العقد"><select className="field-input" value={form.contractId} onChange={e=>setForm({...form,contractId:e.target.value})}>{contracts.filter(c=>c.projectId===form.projectId).map(c=><option key={c.id} value={c.id}>{c.number}</option>)}</select></Field><Field label="رقم الخطة"><input className="field-input" value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></Field><Field label="الإصدار"><input type="number" className="field-input" value={form.revision} onChange={e=>setForm({...form,revision:Number(e.target.value)})}/></Field><Field label="تاريخ الأساس"><input type="date" className="field-input" value={form.baselineDate} onChange={e=>setForm({...form,baselineDate:e.target.value})}/></Field></Form>{rows.length?<Grid>{rows.map(r=><Card key={r.id} code={`${r.number} / R${r.revision}`} title={projects.find(p=>p.id===r.projectId)?.name||'مشروع'} detail={`${r.baselineDate} · ${r.status}`}/>)}</Grid>:<Empty text="لا توجد خطط توريد."/>}</>;
}

function Requirements({company,rows,plans,boq,repository,reload,notify}:{company:Company;rows:MaterialRequirement[];plans:SupplyPlan[];boq:BOQItem[];repository:IndexedDBProcurementRepository;reload:()=>Promise<void>;notify:(x:string)=>void}){
  const [form,setForm]=useState({supplyPlanId:plans[0]?.id||'',projectId:plans[0]?.projectId||'',boqItemId:'',code:'',description:'',unit:'EA',requiredQuantity:0,requiredBy:'',source:'project_plan' as MaterialRequirement['source'],status:'draft' as ProcurementStatus}); const save=async()=>{try{await repository.saveRequirement({...form,companyId:company.id,boqItemId:form.boqItemId||undefined});setForm({...form,code:'',description:'',requiredQuantity:0});notify('تم حفظ احتياج المواد.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر الحفظ')}};
  if(!plans.length)return <Empty text="أنشئ خطة توريد أولًا."/>;
  return <><Form save={save}><Field label="خطة التوريد"><select className="field-input" value={form.supplyPlanId} onChange={e=>{const p=plans.find(x=>x.id===e.target.value)!;setForm({...form,supplyPlanId:p.id,projectId:p.projectId,boqItemId:''})}}>{plans.map(p=><option key={p.id} value={p.id}>{p.number} / R{p.revision}</option>)}</select></Field><Field label="بند BOQ"><select className="field-input" value={form.boqItemId} onChange={e=>setForm({...form,boqItemId:e.target.value})}><option value="">بدون</option>{boq.filter(b=>b.projectId===form.projectId).map(b=><option key={b.id} value={b.id}>{b.code} — {b.description}</option>)}</select></Field><Field label="الكود"><input className="field-input" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></Field><Field label="الوصف"><input className="field-input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="الوحدة"><input className="field-input" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></Field><Field label="الكمية"><input type="number" className="field-input" value={form.requiredQuantity} onChange={e=>setForm({...form,requiredQuantity:Number(e.target.value)})}/></Field><Field label="مطلوب في"><input type="date" className="field-input" value={form.requiredBy} onChange={e=>setForm({...form,requiredBy:e.target.value})}/></Field></Form>{rows.length?<Grid>{rows.map(r=><Card key={r.id} code={r.code} title={r.description} detail={`${r.requiredQuantity} ${r.unit} · ${r.requiredBy} · ${r.status}`}/>)}</Grid>:<Empty text="لا توجد احتياجات."/>}</>;
}

function Requisitions({company,rows,projects,requirements,repository,reload,notify}:{company:Company;rows:PurchaseRequisition[];projects:ProjectRecord[];requirements:MaterialRequirement[];repository:IndexedDBProcurementRepository;reload:()=>Promise<void>;notify:(x:string)=>void}){
  const [form,setForm]=useState({number:'',projectId:projects[0]?.id||'',requirementId:'',description:'',unit:'EA',quantity:0,requiredBy:'',status:'draft' as ProcurementStatus}); const save=async()=>{try{await repository.saveRequisition({...form,companyId:company.id,requirementId:form.requirementId||undefined});setForm({...form,number:'',description:'',quantity:0});notify('تم حفظ طلب الشراء كمسودة.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر الحفظ')}};const move=async(id:string,status:PurchaseRequisition['status'])=>{try{await repository.setRequisitionStatus(id,status);await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر تغيير الحالة')}};
  if(!projects.length)return <Empty text="أنشئ مشروعًا أولًا."/>;
  return <><Form save={save}><Field label="الرقم"><input className="field-input" value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></Field><Field label="المشروع"><select className="field-input" value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value,requirementId:''})}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="الاحتياج"><select className="field-input" value={form.requirementId} onChange={e=>{const r=requirements.find(x=>x.id===e.target.value);setForm({...form,requirementId:e.target.value,description:r?.description||form.description,unit:r?.unit||form.unit,quantity:r?.requiredQuantity||form.quantity,requiredBy:r?.requiredBy||form.requiredBy})}}><option value="">طلب مستقل</option>{requirements.filter(r=>r.projectId===form.projectId).map(r=><option key={r.id} value={r.id}>{r.code}</option>)}</select></Field><Field label="الوصف"><input className="field-input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="الوحدة"><input className="field-input" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></Field><Field label="الكمية"><input type="number" className="field-input" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></Field><Field label="مطلوب في"><input type="date" className="field-input" value={form.requiredBy} onChange={e=>setForm({...form,requiredBy:e.target.value})}/></Field></Form>{rows.length?<Grid>{rows.map(r=><Card key={r.id} code={r.number} title={r.description} detail={`${r.quantity} ${r.unit} · ${r.status}`} actions={<>{r.status==='draft'&&action('إرسال',()=>void move(r.id,'submitted'))}{r.status==='submitted'&&action('اعتماد',()=>void move(r.id,'approved'))}</>}/>)}</Grid>:<Empty text="لا توجد طلبات شراء."/>}</>;
}

function RFQs({company,rows,requisitions,suppliers,repository,reload,notify}:{company:Company;rows:RequestForQuotation[];requisitions:PurchaseRequisition[];suppliers:BusinessParty[];repository:IndexedDBProcurementRepository;reload:()=>Promise<void>;notify:(x:string)=>void}){
  const approved=requisitions.filter(r=>r.status==='approved'); const [form,setForm]=useState({number:'',requisitionId:approved[0]?.id||'',supplierIds:[] as string[],closingDate:'',status:'submitted' as ProcurementStatus}); const save=async()=>{try{await repository.saveRFQ({...form,companyId:company.id});setForm({...form,number:'',supplierIds:[]});notify('تم إصدار RFQ للموردين المختارين.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر الحفظ')}};
  if(!approved.length||!suppliers.length)return <Empty text="RFQ يحتاج طلب شراء معتمدًا وموردًا مسجلًا."/>;
  return <><Form save={save}><Field label="الرقم"><input className="field-input" value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></Field><Field label="طلب الشراء"><select className="field-input" value={form.requisitionId} onChange={e=>setForm({...form,requisitionId:e.target.value})}>{approved.map(r=><option key={r.id} value={r.id}>{r.number}</option>)}</select></Field><Field label="تاريخ الإغلاق"><input type="date" className="field-input" value={form.closingDate} onChange={e=>setForm({...form,closingDate:e.target.value})}/></Field><div className="field-label">الموردون<div className="mt-2 space-y-2">{suppliers.map(s=><label key={s.id} className="flex gap-2 text-xs"><input type="checkbox" checked={form.supplierIds.includes(s.id)} onChange={()=>setForm({...form,supplierIds:form.supplierIds.includes(s.id)?form.supplierIds.filter(id=>id!==s.id):[...form.supplierIds,s.id]})}/>{s.arabicName}</label>)}</div></div></Form>{rows.length?<Grid>{rows.map(r=><Card key={r.id} code={r.number} title={requisitions.find(x=>x.id===r.requisitionId)?.description||'RFQ'} detail={`${r.supplierIds.length} مورد · إغلاق ${r.closingDate} · ${r.status}`}/>)}</Grid>:<Empty text="لا توجد RFQ."/>}</>;
}

function Quotes({company,rows,rfqs,suppliers,repository,reload,notify}:{company:Company;rows:SupplierQuote[];rfqs:RequestForQuotation[];suppliers:BusinessParty[];repository:IndexedDBProcurementRepository;reload:()=>Promise<void>;notify:(x:string)=>void}){
  const [form,setForm]=useState({rfqId:rfqs[0]?.id||'',supplierId:rfqs[0]?.supplierIds[0]||'',quoteNumber:'',quantity:0,unitPrice:0,freight:0,leadTimeDays:0,validUntil:'',selected:false});const selectedRfq=rfqs.find(r=>r.id===form.rfqId);const save=async()=>{try{await repository.saveQuote({...form,companyId:company.id,validUntil:form.validUntil||undefined});setForm({...form,quoteNumber:'',quantity:0,unitPrice:0,freight:0});notify('تم حفظ عرض المورد.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر الحفظ')}};const createPO=async(q:SupplierQuote)=>{const number=window.prompt('رقم أمر الشراء',`PO-${q.quoteNumber}`);if(!number)return;const date=window.prompt('تاريخ التوريد المتوقع بصيغة YYYY-MM-DD',new Date().toISOString().slice(0,10));if(!date)return;try{await repository.selectQuoteAndCreatePO(q.id,number,date);notify('تم اختيار العرض وإنشاء أمر شراء Draft.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر إنشاء أمر الشراء')}};
  if(!rfqs.length)return <Empty text="أنشئ RFQ أولًا."/>;
  return <><Form save={save}><Field label="RFQ"><select className="field-input" value={form.rfqId} onChange={e=>{const r=rfqs.find(x=>x.id===e.target.value)!;setForm({...form,rfqId:r.id,supplierId:r.supplierIds[0]||''})}}>{rfqs.filter(r=>r.status!=='closed').map(r=><option key={r.id} value={r.id}>{r.number}</option>)}</select></Field><Field label="المورد"><select className="field-input" value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}>{(selectedRfq?.supplierIds||[]).map(id=><option key={id} value={id}>{suppliers.find(s=>s.id===id)?.arabicName}</option>)}</select></Field><Field label="رقم العرض"><input className="field-input" value={form.quoteNumber} onChange={e=>setForm({...form,quoteNumber:e.target.value})}/></Field><Field label="الكمية"><input type="number" className="field-input" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></Field><Field label="سعر الوحدة"><input type="number" className="field-input" value={form.unitPrice} onChange={e=>setForm({...form,unitPrice:Number(e.target.value)})}/></Field><Field label="الشحن"><input type="number" className="field-input" value={form.freight} onChange={e=>setForm({...form,freight:Number(e.target.value)})}/></Field><Field label="Lead time بالأيام"><input type="number" className="field-input" value={form.leadTimeDays} onChange={e=>setForm({...form,leadTimeDays:Number(e.target.value)})}/></Field></Form>{rows.length?<Grid>{rows.map(r=><Card key={r.id} code={r.quoteNumber} title={suppliers.find(s=>s.id===r.supplierId)?.arabicName||'مورد'} detail={`الإجمالي ${(r.quantity*r.unitPrice+r.freight).toFixed(2)} · ${r.leadTimeDays} يوم${r.selected?' · مختار':''}`} actions={!r.selected? action('اختيار وإنشاء PO',()=>void createPO(r)):undefined}/>)}</Grid>:<Empty text="لا توجد عروض موردين."/>}</>;
}

function Orders({rows,suppliers,repository,reload,notify}:{rows:PurchaseOrder[];suppliers:BusinessParty[];repository:IndexedDBProcurementRepository;reload:()=>Promise<void>;notify:(x:string)=>void}){const move=async(id:string,status:PurchaseOrder['status'])=>{try{await repository.setPurchaseOrderStatus(id,status);notify('تم تحديث أمر الشراء.');await reload()}catch(e){notify(e instanceof Error?e.message:'تعذر تحديث الحالة')}};return rows.length?<Grid>{rows.map(r=><Card key={r.id} code={r.number} title={r.description} detail={`${suppliers.find(s=>s.id===r.supplierId)?.arabicName||'مورد'} · ${r.quantity} ${r.unit} · ${r.orderedValue.toFixed(2)} · ${r.status}`} actions={r.status==='draft'?action('اعتماد أمر الشراء',()=>void move(r.id,'approved')):undefined}/>)}</Grid>:<Empty text="لا توجد أوامر شراء. اختر عرض مورد لإنشاء الأمر."/>}
